#  SPDX-License-Identifier: Apache-2.0
#  SPDX-FileCopyrightText: Copyright the Vortex contributors

def _debug_array_metadata_dtype(array: object) -> str: ...
def _debug_array_metadata_display_values(array: object) -> str: ...
def _debug_arrow_device_array_capsule_summary(schema: object, device_array: object) -> dict[str, object]: ...
def _debug_consume_arrow_device_array_capsules(
    schema: object, device_array: object
) -> tuple[bool, bool, bool, bool, bool, bool]: ...
def cuda_available() -> bool: ...
def export_device_array(
    array: object, requested_schema: object | None = None, **kwargs: object
) -> tuple[object, object]: ...
