#  SPDX-License-Identifier: Apache-2.0
#  SPDX-FileCopyrightText: Copyright the Vortex contributors

def _debug_array_metadata_dtype(array: object) -> str: ...
def cuda_available() -> bool: ...
def export_device_array(
    array: object, requested_schema: object | None = None, **kwargs: object
) -> tuple[object, object]: ...
