version = 1

[[annotations]]
path = "**/*.sql"
SPDX-FileCopyrightText = "Copyright the Vortex contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/*.csv"
SPDX-FileCopyrightText = "Copyright the Vortex contributors"
SPDX-License-Identifier = "Apache-2.0"

# `insta` snapshot files do not allow leading comment lines.
[[annotations]]
path = "src/snapshots/**.snap"
SPDX-FileCopyrightText = "Copyright the Vortex contributors"
SPDX-License-Identifier = "Apache-2.0"
