language = "C"

header = """
#ifdef __cplusplus
extern "C" {
#endif
"""

trailer = """
#ifdef __cplusplus
}
#endif
"""

[export.rename]
"FFIArray" = "Array"
"FFIArrayStream" = "ArrayStream"
"FFIFile" = "File"

[parse]
parse_deps = true
include = ["vortex", "vortex-dtype"]

