allow-dbg-in-tests = true
allow-expect-in-tests = true
allow-unwrap-in-tests = true
single-char-binding-names-threshold = 2
# We prefer using parking_lot for improved ergonomics and performance.
disallowed-types = ["std::collections::HashMap", "std::collections::HashSet", "std::sync::Mutex", "std::sync::RwLock"]

disallowed-methods = [
    # It uses the default hasher and is very easy to just inline with a faster implementation
    "itertools::Itertools::counts"
    ]
