allow-dbg-in-tests = true
allow-expect-in-tests = true
allow-unwrap-in-tests = true
allow-panic-in-tests = true
absolute-paths-max-segments = 3
single-char-binding-names-threshold = 2
disallowed-types = [
    { path = "std::collections::HashMap", reason = "Use the HashMap in vortex_utils::aliases for better performance" },
    { path = "std::collections::HashSet", reason = "Use the HashSet in vortex_utils::aliases for better performance" },
    { path = "std::sync::Mutex", reason = "Prefer using parking_lot Mutex for improved ergonomics and performance" },
    { path = "std::sync::RwLock", reason = "Prefer using parking_lot RwLock for improved ergonomics and performance" },
]

disallowed-methods = [
    { path = "itertools::Itertools::counts", reason = "It uses the default hasher which is slow for primitives. Just inline the loop for better performance.", allow-invalid = true },
    { path = "std::result::Result::and", reason = "This method is a footgun, especially when working with `Result<Validity>`." },
    { path = "std::thread::available_parallelism", reason = "This function might do an unbounded amount of work, use `vortex_utils::parallelism::get_available_parallelism instead" },
]
