coverage:
  status:
    project: #add everything under here, more options at https://docs.codecov.com/docs/commit-status
      default:
        target: auto #default
        threshold: 0%
        base: auto
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
  after_n_builds: 3

# ignore example binaries
ignore:
  - "**/examples/*.rs"
  - "vortex-bench/**/*.rs"
  - "benchmarks/**/*.rs"
