# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright the Vortex contributors

version = 1

# Everything is licensed under Apache-2.0 by default.
[[annotations]]
path = "**"
precedence = "closest"
SPDX-FileCopyrightText = "Copyright the Vortex contributors"
SPDX-License-Identifier = "Apache-2.0"

# Docs are the exception, and are licensed under CC-BY-4.0.
[[annotations]]
path = "docs/**"
precedence = "override"
SPDX-FileCopyrightText = "Copyright the Vortex contributors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "**/*.md"
precedence = "override"
SPDX-FileCopyrightText = "Copyright the Vortex contributors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "benchmarks-website/**"
precedence = "override"
SPDX-FileCopyrightText = "Copyright the Vortex contributors"
SPDX-License-Identifier = "CC-BY-4.0"
