// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! Downloads the nvCOMP SDK and generates Rust FFI bindings for nvCOMP Zstd.
//!
//! Bindings are generated unconditionally. This allows for development against the
//! CUDA APIs in environments that don't support CUDA.
//!
//! The library is loaded at runtime via libloading.

#![expect(clippy::unwrap_used)]
#![expect(clippy::expect_used)]
#![expect(clippy::panic)]

use std::env;
use std::fs;
use std::io::Cursor;
use std::path::PathBuf;

use xz2::read::XzDecoder;

const NVCOMP_VERSION: &str = "5.1.0.21";
const CUDA_VERSION: &str = "cuda12";

/// Minimal CUDA runtime stub header for bindgen.
const CUDA_RUNTIME_STUB: &str = r#"
#pragma once
struct CUstream_st;
typedef struct CUstream_st *cudaStream_t;
typedef int cudaError_t;
#define cudaSuccess 0
"#;

fn main() {
    println!("cargo:rerun-if-env-changed=CUDA_PATH");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let nvcomp_dir = out_dir.join("nvcomp-sdk");

    // Create CUDA stub header in OUT_DIR for bindgen
    let cuda_stub_dir = out_dir.join("cuda-stub");
    fs::create_dir_all(&cuda_stub_dir).unwrap();
    fs::write(cuda_stub_dir.join("cuda_runtime.h"), CUDA_RUNTIME_STUB).unwrap();

    let (os, arch) = match (env::consts::OS, env::consts::ARCH) {
        ("linux", "x86_64") => ("linux", "x86_64"),
        ("linux", "aarch64") => ("linux", "sbsa"),
        // Fall back to linux-x86_64 to generate bindings for any platform.
        _ => ("linux", "x86_64"),
    };

    let archive_name = format!("nvcomp-{os}-{arch}-{NVCOMP_VERSION}_{CUDA_VERSION}-archive");
    let url = format!(
        "https://developer.download.nvidia.com/compute/nvcomp/redist/nvcomp/{os}-{arch}/{archive_name}.tar.xz"
    );

    let include_dir = nvcomp_dir.join("include");

    if !include_dir.exists() {
        let response = reqwest::blocking::get(&url)
            .unwrap_or_else(|e| panic!("Failed to download nvCOMP: {e}"));

        assert!(
            response.status().is_success(),
            "Failed to download nvCOMP: HTTP {}",
            response.status()
        );

        let bytes = response.bytes().unwrap();

        // Extract tar.xz archive.
        let cursor = Cursor::new(bytes.as_ref());
        let xz = XzDecoder::new(cursor);
        let mut archive = tar::Archive::new(xz);

        let temp_dir = nvcomp_dir.with_extension("tmp");
        fs::create_dir_all(&temp_dir).unwrap();
        archive.unpack(&temp_dir).unwrap();

        // Move extracted content.
        let extracted = temp_dir.join(&archive_name);
        if nvcomp_dir.exists() {
            fs::remove_dir_all(&nvcomp_dir).unwrap();
        }
        fs::rename(&extracted, &nvcomp_dir).unwrap();
        fs::remove_dir_all(&temp_dir).ok();
    }

    // Functions are loaded at runtime via libloading to avoid link-time symbol resolution.
    let bindings = bindgen::Builder::default()
        .header(include_dir.join("nvcomp.h").to_string_lossy())
        .header(include_dir.join("nvcomp/zstd.h").to_string_lossy())
        .clang_arg(format!("-I{}", include_dir.display()))
        .clang_arg(format!("-I{}", cuda_stub_dir.display()))
        .allowlist_type("nvcompStatus_t")
        .allowlist_type("nvcompBatchedZstdDecompressOpts_t")
        .allowlist_type("nvcompDecompressBackend_t")
        .allowlist_function("nvcompBatchedZstdDecompressGetTempSizeAsync")
        .allowlist_function("nvcompBatchedZstdDecompressAsync")
        .dynamic_library_name("NvcompLibrary")
        .dynamic_link_require_all(true)
        .wrap_unsafe_ops(true)
        .blocklist_type("CUstream_st")
        .blocklist_type("cudaStream_t")
        .raw_line("// FFI type definitions for nvCOMP (generated by bindgen).")
        .raw_line("// Functions are loaded at runtime via libloading.")
        .raw_line("")
        .raw_line("pub type cudaStream_t = *mut std::ffi::c_void;")
        .generate()
        .expect("Failed to generate nvcomp bindings");

    bindings.write_to_file(out_dir.join("sys.rs")).unwrap();
}
