from . import _lib
from ._lib.arrays import (
    BinaryTypeArray,
    BoolTypeArray,
    ExtensionTypeArray,
    Float16TypeArray,
    Float32TypeArray,
    Float64TypeArray,
    Int8TypeArray,
    Int16TypeArray,
    Int32TypeArray,
    Int64TypeArray,
    ListTypeArray,
    NullTypeArray,
    StructTypeArray,
    UInt8TypeArray,
    UInt16TypeArray,
    UInt32TypeArray,
    UInt64TypeArray,
    Utf8TypeArray,
)
from ._lib.compress import compress
from ._lib.dtype import (
    BinaryDType,
    BoolDType,
    DType,
    ExtensionDType,
    ListDType,
    NullDType,
    PrimitiveDType,
    StructDType,
    Utf8DType,
    binary,
    bool_,
    float_,
    int_,
    list_,
    null,
    struct,
    uint,
    utf8,
)
from ._lib.encoding import (
    AlpEncoding,
    AlpRdEncoding,
    BoolEncoding,
    ChunkedEncoding,
    ConstantEncoding,
    DateTimePartsEncoding,
    DictEncoding,
    ExtensionEncoding,
    FastLanesBitPackedEncoding,
    FastLanesDeltaEncoding,
    FastLanesForEncoding,
    FsstEncoding,
    ListEncoding,
    NullEncoding,
    PrimitiveEncoding,
    RunEndEncoding,
    SparseEncoding,
    StructEncoding,
    VarBinEncoding,
    VarBinViewEncoding,
    ZigZagEncoding,
)
from ._lib.scalar import (
    BinaryScalar,
    BoolScalar,
    ExtensionScalar,
    ListScalar,
    NullScalar,
    PrimitiveScalar,
    Scalar,
    StructScalar,
    Utf8Scalar,
    scalar,
)
from .arrays import Array, array

assert _lib, "Ensure we eagerly import the Vortex native library"

__all__ = [
    "array",
    "compress",
    # Arrays
    "Array",
    "NullTypeArray",
    "BoolTypeArray",
    "UInt8TypeArray",
    "UInt16TypeArray",
    "UInt32TypeArray",
    "UInt64TypeArray",
    "Int8TypeArray",
    "Int16TypeArray",
    "Int32TypeArray",
    "Int64TypeArray",
    "Float16TypeArray",
    "Float32TypeArray",
    "Float64TypeArray",
    "Utf8TypeArray",
    "BinaryTypeArray",
    "StructTypeArray",
    "ListTypeArray",
    "ExtensionTypeArray",
    # DTypes
    "DType",
    "NullDType",
    "BoolDType",
    "PrimitiveDType",
    "Utf8DType",
    "BinaryDType",
    "StructDType",
    "ListDType",
    "ExtensionDType",
    "null",
    "bool_",
    "int_",
    "uint",
    "float_",
    "utf8",
    "binary",
    "struct",
    "list_",
    # Encodings
    "ConstantEncoding",
    "ChunkedEncoding",
    "NullEncoding",
    "BoolEncoding",
    "PrimitiveEncoding",
    "VarBinEncoding",
    "VarBinViewEncoding",
    "StructEncoding",
    "ListEncoding",
    "ExtensionEncoding",
    "AlpEncoding",
    "AlpRdEncoding",
    "DateTimePartsEncoding",
    "DictEncoding",
    "FsstEncoding",
    "RunEndEncoding",
    "SparseEncoding",
    "ZigZagEncoding",
    "FastLanesBitPackedEncoding",
    "FastLanesDeltaEncoding",
    "FastLanesForEncoding",
    # Scalars
    "scalar",
    "Scalar",
    "NullScalar",
    "BoolScalar",
    "PrimitiveScalar",
    "Utf8Scalar",
    "BinaryScalar",
    "StructScalar",
    "ListScalar",
    "ExtensionScalar",
]
