// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! AVX2 fast paths for the streaming bit-packed compare kernel.
//!
//! Profiling the in-range compare shows two hot steps, both of which are SSE2/scalar at the
//! default `x86-64` target and which together dominate the kernel:
//!
//! 1. **Fused unpack-and-compare** ([`unpack_cmp_block`]). The crates.io `fastlanes` crate is
//!    compiled at baseline `x86-64`, so its
//!    [`BitPackingCompare::unchecked_unpack_cmp`](fastlanes::BitPackingCompare) inner loop
//!    auto-vectorises only to SSE2 (128-bit, 4×`u32`/op). We can't change how the external
//!    crate is compiled, but [`fastlanes::unpack!`] is an exported macro, so we re-expand the
//!    exact same kernel inside a `#[target_feature(enable = "avx2")]` function — byte-identical
//!    work, 256-bit codegen.
//!
//! 2. **Bool→bitmask packing** ([`pack_block_bools`]). Folding the per-element bools into the
//!    output `BitBuffer` via the scalar [`vortex_buffer::pack_bools_into_words`] is the single
//!    largest cost; a `vpmovmskb` packer replaces 64 scalar shift-ORs per word with a couple
//!    of vector ops.
//!
//! Both fast paths are selected at runtime via [`std::arch::is_x86_feature_detected`]; non-AVX2
//! hosts (and non-`x86_64` targets) fall back to the stock scalar/SSE2 implementations.

use fastlanes::BitPackingCompare;
use fastlanes::FastLanesComparable;

#[cfg(target_arch = "x86_64")]
mod avx2 {
    // The `unpack!` row expansion and the per-width dispatch are intentionally large, matching
    // the structure of the fastlanes kernels they mirror.
    #![allow(clippy::cognitive_complexity)]

    use fastlanes::FastLanes;
    use fastlanes::FastLanesComparable;

    // Each per-width kernel mirrors `fastlanes`'s `unpack_cmp::<W, B>` — the per-lane
    // [`fastlanes::unpack!`] loop — but is compiled with AVX2 enabled so the inner loop
    // auto-vectorises to 256-bit vectors. Like fastlanes, the width-generic kernel is
    // `#[inline(never)]`: each width gets its own small stack frame, so the dispatcher that
    // matches over all widths does not accumulate a giant (stack-overflowing) frame in debug
    // builds. The kernels are hand written per physical type rather than generated by a
    // wrapper `macro_rules!`, because `unpack!` captures its closure parameters as
    // `$idx`/`$elem` and those `$`-tokens cannot pass through an enclosing transcriber.
    //
    // # Safety (every function here)
    // The host must support AVX2, `input.len()` must equal `128 * W / size_of::<T>()`, and
    // `W` (or `width`) must be `<= 8 * size_of::<T>()`.

    macro_rules! gen_dispatch {
        ($T:ty, $run:ident, $kernel:ident) => {
            /// Width dispatcher: forwards to the per-width AVX2 kernel.
            pub(super) unsafe fn $run<V, F>(
                width: usize,
                input: &[$T],
                output: &mut [bool; 1024],
                cmp: F,
                value: V,
            ) where
                V: FastLanesComparable<Bitpacked = $T>,
                F: Fn(V, V) -> bool,
            {
                paste::paste!(fastlanes::seq_t!(W in $T {
                    match width {
                        // SAFETY: forwarded — caller guarantees AVX2 and the buffer invariants.
                        #(W => unsafe { $kernel::<W, V, F>(input, output, cmp, value) },)*
                        _ => unreachable!("unsupported bit width {width}"),
                    }
                }));
            }
        };
    }

    // Per-width `#[inline(never)]` AVX2 kernels, hand written per physical type (the `unpack!`
    // closure params `$idx`/`$elem` cannot pass through a `macro_rules!` transcriber).

    #[target_feature(enable = "avx2")]
    #[inline(never)]
    unsafe fn run_u8_w<const W: usize, V, F>(
        input: &[u8],
        output: &mut [bool; 1024],
        cmp: F,
        value: V,
    ) where
        V: FastLanesComparable<Bitpacked = u8>,
        F: Fn(V, V) -> bool,
    {
        for lane in 0..<u8 as FastLanes>::LANES {
            fastlanes::unpack!(u8, W, input, lane, |$idx, $elem| {
                output[$idx] = cmp(V::as_unpacked($elem), value);
            });
        }
    }

    #[target_feature(enable = "avx2")]
    #[inline(never)]
    unsafe fn run_u16_w<const W: usize, V, F>(
        input: &[u16],
        output: &mut [bool; 1024],
        cmp: F,
        value: V,
    ) where
        V: FastLanesComparable<Bitpacked = u16>,
        F: Fn(V, V) -> bool,
    {
        for lane in 0..<u16 as FastLanes>::LANES {
            fastlanes::unpack!(u16, W, input, lane, |$idx, $elem| {
                output[$idx] = cmp(V::as_unpacked($elem), value);
            });
        }
    }

    #[target_feature(enable = "avx2")]
    #[inline(never)]
    unsafe fn run_u32_w<const W: usize, V, F>(
        input: &[u32],
        output: &mut [bool; 1024],
        cmp: F,
        value: V,
    ) where
        V: FastLanesComparable<Bitpacked = u32>,
        F: Fn(V, V) -> bool,
    {
        for lane in 0..<u32 as FastLanes>::LANES {
            fastlanes::unpack!(u32, W, input, lane, |$idx, $elem| {
                output[$idx] = cmp(V::as_unpacked($elem), value);
            });
        }
    }

    #[target_feature(enable = "avx2")]
    #[inline(never)]
    unsafe fn run_u64_w<const W: usize, V, F>(
        input: &[u64],
        output: &mut [bool; 1024],
        cmp: F,
        value: V,
    ) where
        V: FastLanesComparable<Bitpacked = u64>,
        F: Fn(V, V) -> bool,
    {
        for lane in 0..<u64 as FastLanes>::LANES {
            fastlanes::unpack!(u64, W, input, lane, |$idx, $elem| {
                output[$idx] = cmp(V::as_unpacked($elem), value);
            });
        }
    }

    gen_dispatch!(u8, run_u8, run_u8_w);
    gen_dispatch!(u16, run_u16, run_u16_w);
    gen_dispatch!(u32, run_u32, run_u32_w);
    gen_dispatch!(u64, run_u64, run_u64_w);
}

/// Maps a value type to its AVX2 fused unpack-and-compare kernel. Implemented for every
/// bit-packable integer type; on non-`x86_64` targets the kernel method does not exist and
/// [`unpack_cmp_block`] never references it.
pub(crate) trait UnpackCmpAvx2: FastLanesComparable
where
    Self::Bitpacked: BitPackingCompare,
{
    /// Run the AVX2 fused unpack-and-compare kernel for this type.
    ///
    /// # Safety
    /// AVX2 must be available on the host, and `input.len()` must equal
    /// `128 * width / size_of::<Self::Bitpacked>()` with `width` a supported bit width.
    #[cfg(target_arch = "x86_64")]
    unsafe fn unpack_cmp_avx2<F>(
        width: usize,
        input: &[Self::Bitpacked],
        output: &mut [bool; 1024],
        cmp: F,
        value: Self,
    ) where
        F: Fn(Self, Self) -> bool;
}

#[cfg(target_arch = "x86_64")]
macro_rules! impl_unpack_cmp_avx2 {
    ($V:ty, $run:ident) => {
        impl UnpackCmpAvx2 for $V {
            #[inline]
            unsafe fn unpack_cmp_avx2<F>(
                width: usize,
                input: &[<$V as FastLanesComparable>::Bitpacked],
                output: &mut [bool; 1024],
                cmp: F,
                value: $V,
            ) where
                F: Fn($V, $V) -> bool,
            {
                // SAFETY: forwarded — caller guarantees AVX2 and the buffer invariants.
                unsafe { avx2::$run(width, input, output, cmp, value) }
            }
        }
    };
}

#[cfg(not(target_arch = "x86_64"))]
macro_rules! impl_unpack_cmp_avx2 {
    ($V:ty, $run:ident) => {
        impl UnpackCmpAvx2 for $V {}
    };
}

impl_unpack_cmp_avx2!(u8, run_u8);
impl_unpack_cmp_avx2!(i8, run_u8);
impl_unpack_cmp_avx2!(u16, run_u16);
impl_unpack_cmp_avx2!(i16, run_u16);
impl_unpack_cmp_avx2!(u32, run_u32);
impl_unpack_cmp_avx2!(i32, run_u32);
impl_unpack_cmp_avx2!(u64, run_u64);
impl_unpack_cmp_avx2!(i64, run_u64);

/// Fused unpack-and-compare for one 1024-element FastLanes block: compare every unpacked
/// value against `value` with `cmp`, writing per-element bools into `output`. Uses the AVX2
/// kernel when the host supports it, otherwise the stock SSE2 `unchecked_unpack_cmp`.
///
/// # Safety
/// `input.len()` must equal `128 * width / size_of::<V::Bitpacked>()` and `width` must be a
/// supported bit width, matching the contract of
/// [`fastlanes::BitPackingCompare::unchecked_unpack_cmp`].
#[inline]
pub(crate) unsafe fn unpack_cmp_block<V, F>(
    width: usize,
    input: &[V::Bitpacked],
    output: &mut [bool; 1024],
    cmp: F,
    value: V,
) where
    V: UnpackCmpAvx2,
    V::Bitpacked: BitPackingCompare,
    F: Fn(V, V) -> bool,
{
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2") {
        // SAFETY: AVX2 detected; the buffer invariants are the caller's contract.
        unsafe {
            V::unpack_cmp_avx2(width, input, output, cmp, value);
        }
        return;
    }

    // SAFETY: the buffer invariants are the caller's contract.
    unsafe {
        <V::Bitpacked as BitPackingCompare>::unchecked_unpack_cmp(width, input, output, cmp, value);
    }
}

/// Pack a full block of 1024 logical-order bools into the first 16 little-endian `u64` words
/// of `dst` (`dst[i]` holds bools `64*i .. 64*i + 64`), assigning each word (the destination
/// need not be zeroed). Uses an AVX2 byte-movemask when available, else a scalar fallback.
///
/// This is the hot bool→bitmask step of the streaming compare: profiling shows the scalar
/// [`vortex_buffer::pack_bools_into_words`] dominates the in-range compare, so the full-chunk
/// case (always 64-bit aligned) is packed with `vpmovmskb` instead.
///
/// `dst` must have at least 16 elements.
#[inline]
pub(crate) fn pack_block_bools(dst: &mut [u64], bools: &[bool; 1024]) {
    #[cfg(target_arch = "x86_64")]
    if std::arch::is_x86_feature_detected!("avx2") {
        // SAFETY: AVX2 detected; `bools` is 1024 bytes and `dst` has >= 16 words.
        unsafe {
            pack_block_bools_avx2(dst, bools);
        }
        return;
    }

    pack_block_bools_scalar(dst, bools);
}

fn pack_block_bools_scalar(dst: &mut [u64], bools: &[bool; 1024]) {
    for (word, chunk) in dst.iter_mut().zip(bools.chunks_exact(64)) {
        let mut packed = 0u64;
        for (bit, &b) in chunk.iter().enumerate() {
            packed |= (b as u64) << bit;
        }
        *word = packed;
    }
}

#[cfg(target_arch = "x86_64")]
#[target_feature(enable = "avx2")]
fn pack_block_bools_avx2(dst: &mut [u64], bools: &[bool; 1024]) {
    use std::arch::x86_64::_mm256_cmpgt_epi8;
    use std::arch::x86_64::_mm256_loadu_si256;
    use std::arch::x86_64::_mm256_movemask_epi8;
    use std::arch::x86_64::_mm256_setzero_si256;

    // `bool` is one byte (0 or 1). `cmpgt(b, 0)` yields 0xFF for true / 0x00 for false, then
    // `movemask` extracts one bit per byte — 32 bools per 256-bit load.
    let src = bools.as_ptr().cast::<i8>();
    let zero = _mm256_setzero_si256();
    for (i, word) in dst.iter_mut().take(16).enumerate() {
        let base = i * 64;
        // SAFETY: base + 64 <= 1024, so both 32-byte loads stay within `bools`.
        let (lo, hi) = unsafe {
            (
                _mm256_loadu_si256(src.add(base).cast()),
                _mm256_loadu_si256(src.add(base + 32).cast()),
            )
        };
        let lo_mask = _mm256_movemask_epi8(_mm256_cmpgt_epi8(lo, zero)) as u32 as u64;
        let hi_mask = _mm256_movemask_epi8(_mm256_cmpgt_epi8(hi, zero)) as u32 as u64;
        *word = lo_mask | (hi_mask << 32);
    }
}

#[cfg(test)]
mod tests {
    use super::pack_block_bools;
    use super::pack_block_bools_scalar;

    fn reference(bools: &[bool; 1024]) -> [u64; 16] {
        let mut words = [0u64; 16];
        for (i, b) in bools.iter().enumerate() {
            if *b {
                words[i / 64] |= 1u64 << (i % 64);
            }
        }
        words
    }

    #[test]
    fn pack_block_matches_reference() {
        // A pattern that exercises every bit position within each word.
        let bools: [bool; 1024] = std::array::from_fn(|i| (i * 2654435761) % 3 == 0);
        let want = reference(&bools);

        let mut scalar = [0u64; 16];
        pack_block_bools_scalar(&mut scalar, &bools);
        assert_eq!(scalar, want, "scalar packer mismatch");

        // `pack_block_bools` uses the AVX2 path on capable hosts, scalar otherwise; either
        // way it must equal the reference.
        let mut dispatched = [0u64; 16];
        pack_block_bools(&mut dispatched, &bools);
        assert_eq!(dispatched, want, "dispatched packer mismatch");
    }

    #[test]
    fn pack_block_all_set_and_clear() {
        let all_true = [true; 1024];
        let mut words = [0u64; 16];
        pack_block_bools(&mut words, &all_true);
        assert_eq!(words, [u64::MAX; 16]);

        let all_false = [false; 1024];
        let mut words = [0xDEADBEEFu64; 16];
        pack_block_bools(&mut words, &all_false);
        assert_eq!(words, [0u64; 16]);
    }
}
