// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! FFI bindings to CUB filter operations (generated by bindgen at build time).

#![allow(rustdoc::broken_intra_doc_links)]
#![allow(clippy::absolute_paths)]

include!(concat!(env!("OUT_DIR"), "/sys.rs"));
