// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

#![allow(clippy::unwrap_used)]
#![allow(clippy::expect_used)]
#![allow(clippy::panic)]

//! Build script for vortex-clickhouse.
//!
//! This script:
//! 1. Downloads ClickHouse source code (for headers) - optional
//! 2. Generates Rust bindings from C++ headers (bindgen) - when headers are available
//! 3. Creates placeholder cpp.rs for now

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-env-changed=CLICKHOUSE_VERSION");
    println!("cargo:rerun-if-env-changed=CLICKHOUSE_SOURCE_DIR");

    let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());

    // For now, we'll create a minimal cpp.rs since we don't have ClickHouse headers yet
    // The full implementation will require ClickHouse headers
    let cpp_rs_content = r#"// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! FFI bindings for ClickHouse.
//!
//! This module is auto-generated by bindgen when ClickHouse headers are available.
//! For now, it contains placeholder definitions.

#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]

// Placeholder types - will be replaced by bindgen-generated code
// when ClickHouse headers are available.

/// Result status for operations.
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum vortex_ch_state {
    Success = 0,
    Error = 1,
}
"#;

    let cpp_rs_path = crate_dir.join("src/cpp.rs");
    let existing = fs::read_to_string(&cpp_rs_path).unwrap_or_default();
    if existing != cpp_rs_content {
        fs::write(&cpp_rs_path, cpp_rs_content).expect("Failed to write cpp.rs");
    }

    // Watch C/C++ source files for changes.
    for entry in walkdir::WalkDir::new(crate_dir.join("cpp"))
        .into_iter()
        .flatten()
    {
        if entry
            .path()
            .extension()
            .is_some_and(|ext| ext == "cpp" || ext == "h" || ext == "hpp")
        {
            println!("cargo:rerun-if-changed={}", entry.path().display());
        }
    }
}
