// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

use std::fs;
use std::path::Path;

pub mod benchmark;
pub mod schema;
pub mod tpchgen;

use vortex::error::VortexExpect;

pub const TPC_H_ROW_COUNT_ARRAY_LENGTH: usize = 23;
// All EXPECTED_ROW_COUNTS_SF* arrays use index 0 as a dummy so that Query N's row count is at
// index N. They were generated by executing the SQL in each query file using duckdb against the
// parquet files produced by `tpchgen` in this crate (i.e. table names replaced by
// "$NAME.parquet").
pub const EXPECTED_ROW_COUNTS_SF0_01: [usize; TPC_H_ROW_COUNT_ARRAY_LENGTH] = [
    0, 4, 4, 10, 5, 5, 1, 4, 2, 173, 20, 359, 2, 33, 1, 1, 296, 1, 2, 1, 1, 1, 7,
];
pub const EXPECTED_ROW_COUNTS_SF0_1: [usize; TPC_H_ROW_COUNT_ARRAY_LENGTH] = [
    0, 4, 44, 10, 5, 5, 1, 4, 2, 175, 20, 2541, 2, 37, 1, 1, 2762, 1, 5, 1, 9, 47, 7,
];
pub const EXPECTED_ROW_COUNTS_SF1: [usize; TPC_H_ROW_COUNT_ARRAY_LENGTH] = [
    0, 4, 100, 10, 5, 5, 1, 4, 2, 175, 20, 1048, 2, 42, 1, 1, 18314, 1, 57, 1, 186, 100, 7,
];
pub const EXPECTED_ROW_COUNTS_SF10: [usize; TPC_H_ROW_COUNT_ARRAY_LENGTH] = [
    0, 4, 100, 10, 5, 5, 1, 4, 2, 175, 20, 0, 2, 46, 1, 1, 27840, 1, 100, 1, 1804, 100, 7,
];

pub fn tpch_queries() -> impl Iterator<Item = (usize, String)> {
    (1..=22).map(|q| (q, tpch_query(q)))
}

// A few tpch queries have multiple statements, this handles that
fn tpch_query(query_idx: usize) -> String {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tpch")
        .join(format!("q{query_idx}"))
        .with_extension("sql");
    fs::read_to_string(manifest_dir).vortex_expect("cannot load tpch query from file")
}
