name: "Prepare vortex dependencies for java"
description: "Install required packages for vortex java build"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        apt update
        apt install -y wget curl build-essential unzip clang
    - name: Print GLIBC version
      shell: bash
      run: ldd --version
    - name: Verify GLIBC version
      shell: bash
      run: |
        set -eux

        ldd --version | grep 'GLIBC 2.31'
