#  SPDX-License-Identifier: Apache-2.0
#  SPDX-FileCopyrightText: Copyright the Vortex contributors

from typing import final, overload

import numpy as np
import pandas as pd
import polars as pl
import pyarrow as pa
from typing_extensions import override

from .dtype import DType, PType
from .expr import Expr
from .scalar import Scalar, ScalarPyType
from .serde import ArrayContext

class Array:
    def __lt__(self, other: Array) -> Array: ...
    def __le__(self, other: Array) -> Array: ...
    def __gt__(self, other: Array) -> Array: ...
    def __ge__(self, other: Array) -> Array: ...
    @override
    def __eq__(self, other: Array) -> Array: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    @override
    def __ne__(self, other: Array) -> Array: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, key: int) -> Scalar: ...
    @overload
    def __getitem__(self, key: slice) -> Array: ...
    def __arrow_c_array__(self, requested_schema: object | None = None) -> tuple[object, object]: ...
    def __arrow_c_stream__(self, requested_schema: object | None = None) -> object: ...
    @staticmethod
    def from_arrow(
        obj: pa.Array[pa.Scalar[pa.DataType]] | pa.ChunkedArray[pa.Scalar[pa.DataType]] | pa.Table,
    ) -> Array: ...
    @staticmethod
    def from_range(obj: range, *, dtype: DType | None = None) -> Array: ...
    def to_arrow_array(self) -> pa.Array[pa.Scalar[pa.DataType]]: ...
    @property
    def id(self) -> str: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def dtype(self) -> DType: ...
    @property
    def null_count(self) -> int: ...
    def filter(self, mask: Array) -> Array: ...
    def scalar_at(self, index: int) -> Scalar: ...
    def take(self, indices: Array) -> Array: ...
    def slice(self, start: int, end: int) -> Array: ...
    def cast(self, dtype: DType) -> Array: ...
    def fill_null(self, value: Scalar | ScalarPyType) -> Array: ...
    def is_null(self) -> Array: ...
    def is_not_null(self) -> Array: ...
    def display_tree(self) -> str: ...
    def to_arrow_table(self) -> pa.Table: ...
    def to_numpy(self, *, zero_copy_only: bool = True) -> np.ndarray: ...
    def to_pandas(self) -> pd.DataFrame: ...
    def to_polars_dataframe(self) -> pl.DataFrame: ...
    def to_polars_series(self) -> pl.Series: ...
    def to_pylist(self) -> list[ScalarPyType]: ...
    def serialize(self, ctx: ArrayContext) -> bytes: ...
    def apply(self, expr: Expr) -> Array: ...

class NativeArray(Array): ...

class PythonArray(Array):
    def __init__(self, len: int, dtype: DType) -> None: ...

@final
class NullArray(Array): ...

@final
class BoolArray(Array): ...

@final
class PrimitiveArray(Array):
    @property
    def ptype(self) -> PType: ...

@final
class DecimalArray(Array):
    @property
    def precision(self) -> int: ...
    @property
    def scale(self) -> int: ...

@final
class VarBinArray(Array): ...

@final
class VarBinViewArray(Array): ...

@final
class StructArray(Array):
    def field(self, name: str) -> Array: ...
    def names(self) -> list[str]: ...

@final
class ListArray(Array): ...

@final
class FixedSizeListArray(Array): ...

@final
class ExtensionArray(Array): ...

@final
class ConstantArray(Array):
    def scalar(self) -> Scalar: ...

@final
class ChunkedArray(Array):
    def chunks(self) -> list[Array]: ...

@final
class ByteBoolArray(Array): ...

@final
class SequenceArray(Array): ...

@final
class SparseArray(Array): ...

@final
class AlpArray(Array): ...

@final
class AlpRdArray(Array): ...

@final
class DateTimePartsArray(Array): ...

@final
class DictArray(Array): ...

@final
class FsstArray(Array): ...

@final
class RunEndArray(Array): ...

@final
class ZigZagArray(Array):
    @staticmethod
    def encode(array: Array) -> Array: ...

@final
class FastLanesBitPackedArray(Array):
    @property
    def bit_width(self) -> int: ...

@final
class FastLanesDeltaArray(Array): ...

@final
class FastLanesFoRArray(Array): ...
