#  SPDX-License-Identifier: Apache-2.0
#  SPDX-FileCopyrightText: Copyright the Vortex contributors

def set_worker_threads(n: int) -> None: ...
def set_worker_threads_to_available_parallelism() -> None: ...
def worker_count() -> int: ...
