from typing import final

import pyarrow as pa

import vortex as vx

@final
class ArrayParts:
    @staticmethod
    def parse(data: bytes) -> ArrayParts: ...
    @property
    def metadata(self) -> bytes | None: ...
    @property
    def nbuffers(self) -> int: ...
    @property
    def buffers(self) -> list[pa.Buffer]: ...
    @property
    def nchildren(self) -> int: ...
    @property
    def children(self) -> list[ArrayParts]: ...
    def decode(self, ctx: ArrayContext, dtype: vx.DType, len: int) -> pa.Array: ...

@final
class ArrayContext:
    def __len__(self): ...
