// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

use std::fs::File;
use std::io::Write;
use std::path::Path;

use fastlanes::FastLanes;

use crate::indent::IndentedWriter;

fn generate_kernel_for_width<T: FastLanes, W: Write>(
    output: &mut IndentedWriter<W>,
    bit_width: usize,
    thread_count: usize,
) -> anyhow::Result<()> {
    let bits = <T>::T;
    let lanes = T::LANES;
    let per_thread_loop_count = lanes / thread_count;

    writeln!(
        output,
        "extern \"C\" __global__ void fls_unpack_{bit_width}bw_{bits}ow_{thread_count}t(const uint{bits}_t *__restrict full_in, uint{bits}_t *__restrict full_out) {{"
    )?;

    output.indent(|output| {
        writeln!(output, "int i = threadIdx.x;")?;
        writeln!(output, "auto in = full_in + (blockIdx.x * (128 * {bit_width} / sizeof(uint{bits}_t)));")?;
        writeln!(output, "auto out = full_out + (blockIdx.x * 1024);")?;
        if bit_width == 0 {
            writeln!(output, "uint{bits}_t zero = 0ULL;")?;
            writeln!(output)?;
            for thread_lane in 0..per_thread_loop_count {
                for row in 0..bits {
                    writeln!(output, "out[INDEX({row}, (i * {per_thread_loop_count} + {thread_lane}))] = zero;")?;
                }
            }
        } else if bit_width == bits {
            writeln!(output)?;
            for thread_lane in 0..per_thread_loop_count {
                for row in 0..bits {
                    writeln!(
                        output,
                        "out[INDEX({row}, (i * {per_thread_loop_count} + {thread_lane}))] = in[{lanes} * {row} + (i * {per_thread_loop_count} + {thread_lane})];",
                    )?;
                }
            }
        } else {
            writeln!(output, "uint{bits}_t src;")?;
            writeln!(output, "uint{bits}_t tmp;")?;

            for thread_lane in 0..per_thread_loop_count {
                writeln!(output)?;
                writeln!(output, "src = in[i * {per_thread_loop_count} + {thread_lane}];")?;
                for row in 0..bits {
                    let curr_word = (row * bit_width) / bits;
                    let next_word = ((row + 1) * bit_width) / bits;
                    let shift = (row * bit_width) % bits;

                    if next_word > curr_word {
                        let remaining_bits = ((row + 1) * bit_width) % bits;
                        let current_bits = bit_width - remaining_bits;
                        writeln!(
                            output,
                            "tmp = (src >> {shift}) & MASK(uint{bits}_t, {current_bits});"
                        )?;

                        if next_word < bit_width {
                            writeln!(output, "src = in[i * {per_thread_loop_count} + {thread_lane} + {lanes} * {next_word}];")?;
                            writeln!(
                                output,
                                "tmp |= (src & MASK(uint{bits}_t, {remaining_bits})) << {current_bits};"
                            )?;
                        }
                    } else {
                        writeln!(
                            output,
                            "tmp = (src >> {shift}) & MASK(uint{bits}_t, {bit_width});"
                        )?;
                    }

                    writeln!(output, "out[INDEX({row}, (i * {per_thread_loop_count} + {thread_lane}))] = tmp;")?;
                }
            }
        }
        Ok(())
    })?;

    writeln!(output, "}}")?;
    Ok(())
}

fn generate_unpack_for_width<T: FastLanes, W: Write>(
    output: &mut IndentedWriter<W>,
    thread_count: usize,
) -> anyhow::Result<()> {
    writeln!(
        output,
        "// Auto-generated by fls-gpu-kernel-gen. Do not edit by hand!"
    )?;
    writeln!(output, "#include <cuda.h>")?;
    writeln!(output, "#include <cuda_runtime.h>")?;
    writeln!(output, "#include <stdint.h>")?;
    writeln!(output, "#include \"fastlanes_common.cuh\"")?;
    writeln!(output)?;

    for bit_width in 0..=<T>::T {
        generate_kernel_for_width::<T, _>(output, bit_width, thread_count)?;
        writeln!(output)?;
    }

    Ok(())
}

pub fn generate_unpack<T: FastLanes>(output_dir: &Path, thread_count: usize) -> anyhow::Result<()> {
    let cu_filename = format!("gen/fls_{}_bit_unpack.cu", T::T);
    let cu_path = output_dir.join(&cu_filename);
    let mut cu_file = File::create(&cu_path)?;
    let mut cu_writer = IndentedWriter::new(&mut cu_file);
    generate_unpack_for_width::<T, _>(&mut cu_writer, thread_count)?;
    Ok(())
}
