[target.'cfg(target_family="unix")']
rustflags = [
    "-C", "force-frame-pointers=yes",
]

[alias]
xtask = "run -p xtask --"
vx = "run -p vortex-tui --"

[publish]
# NOTE(aduffy): we run into frequent issues auto-releasing our workspace
# to crates.io, the default timeout = 60 seconds. Setting this to zero
# means that it will block indefinitely and this config override is
# necessary for using the -Zpublish-timeout setting.
# See https://doc.rust-lang.org/beta/cargo/reference/unstable.html#publish-timeout
timeout = 3600

# Environment variables for PyO3. Ensures reproducible builds and avoids spurious recompilations.
[env]
PYO3_ENVIRONMENT_SIGNATURE = { value = "cpython-3.11-64bit", force = true }

[cache.global-clean]
# Anything older than this duration will be deleted in the source cache.
max-src-age = "1 week"
# Anything older than this duration will be deleted in the compressed crate cache.
max-crate-age = "1 week"
# Any git checkout older than this duration will be deleted from the checkout cache.
max-git-co-age = "1 week"
# Any index older than this duration will be deleted from the index cache.
max-index-age = "1 month"
# Any git clone older than this duration will be deleted from the git cache.
max-git-db-age = "1 month"
