[target.'cfg(target_family="unix")']
rustflags = [
    "-C", "force-frame-pointers=yes",
]

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"', '-C', 'target-feature=+atomics']

[alias]
xtask = "run -p xtask --"
vx = "run -p vortex-tui --"

[publish]
# NOTE(aduffy): we run into frequent issues auto-releasing our workspace
# to crates.io, the default timeout = 60 seconds. Setting this to zero
# means that it will block indefinitely and this config override is
# necessary for using the -Zpublish-timeout setting.
# See https://doc.rust-lang.org/beta/cargo/reference/unstable.html#publish-timeout
timeout = 3600
