from typing import Any, final

import polars as pl

import vortex as vx

@final
class Expr: ...

def column(name: str) -> Expr: ...
def ident() -> Expr: ...
def literal(dtype: vx.DType, value: Any) -> Expr: ...
def _expr_from_polars(expr: pl.Expr) -> Expr: ...
