import vortex as vx

class ArrayIterator:
    def dtype(self) -> vx.DType: ...
    def read_all(self) -> vx.Array: ...
    def __iter__(self) -> ArrayIterator: ...
    def __next__(self) -> vx.Array: ...
