from collections.abc import Iterator
from typing import final

import vortex as vx

@final
class ArrayIterator:
    @property
    def dtype(self) -> vx.DType: ...
    def read_all(self) -> vx.Array: ...
    def __iter__(self) -> ArrayIterator: ...
    def __next__(self) -> vx.Array: ...
    @staticmethod
    def from_iter(dtype: vx.DType, iter: Iterator[vx.Array]) -> ArrayIterator: ...
