class Buffer:
    def into_python(self, *, recursive=False) -> bytes: ...

class BufferString:
    def into_python(self, *, recursive=False) -> str: ...

class VortexList:
    def into_python(self, *, recursive=False) -> list: ...

class VortexStruct:
    def into_python(self, *, recursive=False) -> dict: ...
