from typing import Any

def scalar(value: Any) -> Scalar: ...

class Scalar: ...

class BoolScalar:
    def as_py(self) -> bool | None: ...

class Buffer:
    def into_python(self, *, recursive=False) -> bytes: ...

class BufferString:
    def into_python(self, *, recursive=False) -> str: ...

class VortexList:
    def into_python(self, *, recursive=False) -> list: ...

class VortexStruct:
    def into_python(self, *, recursive=False) -> dict: ...
