// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! Deterministic generator for the canonical read-boundary benchmark file.
//!
//! Both the `read_boundary` Divan bench and the `gen_bench_data` example write/read the SAME file
//! so the Rust "native floor" and the Java JMH benchmark (`VortexJniReadBenchmark`) measure reads of
//! the exact same bytes. The Gradle `generateBenchFile` task runs the example to produce it, then
//! points the JMH fork at it via `-Dvortex.jni.bench.file`.
//!
//! The table is six columns over [`ROWS`] rows — `id`, `x` (int64), `y`, `z` (float64), and `cat`,
//! `tag` (Utf8View) — generated by a fixed formula (no RNG) so the file is reproducible: `id` is
//! sequential, `cat` is a periodic 16-value low-cardinality column kept non-null so `cat = 'alpha'`
//! has selectivity exactly `1/|CATS|`, and `tag` is high-cardinality with a 10% null rate.

use std::path::Path;
use std::path::PathBuf;

use vortex::VortexSessionDefault;
use vortex::array::ArrayRef;
use vortex::array::IntoArray;
use vortex::array::arrays::ChunkedArray;
use vortex::array::arrays::PrimitiveArray;
use vortex::array::arrays::StructArray;
use vortex::array::arrays::VarBinViewArray;
use vortex::array::validity::Validity;
use vortex::dtype::FieldNames;
use vortex::error::VortexResult;
use vortex::error::vortex_err;
use vortex::file::WriteOptionsSessionExt;
use vortex::io::runtime::BlockingRuntime;
use vortex::io::runtime::current::CurrentThreadRuntime;
use vortex::io::session::RuntimeSessionExt;
use vortex::session::VortexSession;

/// Rows in the canonical table. Must match the JMH side's `BenchData.ROWS`.
pub const ROWS: usize = 2_000_000;
/// Rows per Arrow batch handed to the writer.
pub const WRITE_CHUNK: usize = 65_536;
/// 16 low-cardinality category values; `cat = 'alpha'` matches exactly `ROWS / 16` rows.
pub const CATS: [&str; 16] = [
    "alpha", "bravo", "charlie", "delta", "echo", "foxtrot", "golf", "hotel", "india", "juliet",
    "kilo", "lima", "mike", "november", "oscar", "papa",
];

/// Absolute path of the canonical file, shared with the Gradle/JMH side.
///
/// Honors `VORTEX_JNI_BENCH_FILE`; otherwise defaults to `<workspace>/target/vortex-jni-bench/
/// data.vortex` (the same location the Gradle task passes), so a standalone `cargo bench` and a
/// `./gradlew :vortex-jni:jmh` run resolve to the same file.
pub fn default_path() -> PathBuf {
    if let Ok(path) = std::env::var("VORTEX_JNI_BENCH_FILE") {
        return PathBuf::from(path);
    }
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../target/vortex-jni-bench/data.vortex")
}

/// Build one `[start, end)` slice of the canonical table as a Vortex struct array.
fn build_chunk(start: usize, end: usize) -> ArrayRef {
    let id = PrimitiveArray::from_iter((start..end).map(|r| r as i64)).into_array();
    // Deterministic spread across [0, 1_000_000); a fixed multiplicative hash, no RNG.
    let xs = PrimitiveArray::from_iter(
        (start..end).map(|r| (r as i64).wrapping_mul(2_654_435_761).rem_euclid(1_000_000)),
    )
    .into_array();
    let ys =
        PrimitiveArray::from_iter((start..end).map(|r| (r % 1000) as f64 / 1000.0)).into_array();
    let zs = PrimitiveArray::from_iter((start..end).map(|r| ((r / 1000) % 1000) as f64 / 1000.0))
        .into_array();
    // cat stays non-null and periodic so filter selectivity is exactly 1/|CATS|.
    let cat =
        VarBinViewArray::from_iter_str((start..end).map(|r| CATS[r % CATS.len()])).into_array();
    // tag carries nulls (every 10th row) and high-cardinality values to exercise a validity buffer.
    let tag = VarBinViewArray::from_iter_nullable_str((start..end).map(|r| {
        if r % 10 == 0 {
            None
        } else {
            Some(r.to_string())
        }
    }))
    .into_array();

    StructArray::new(
        FieldNames::from(["id", "x", "y", "z", "cat", "tag"]),
        vec![id, xs, ys, zs, cat, tag],
        end - start,
        Validity::NonNullable,
    )
    .into_array()
}

/// Build the canonical six-column table as a chunked array of [`WRITE_CHUNK`]-row chunks.
fn build_table() -> VortexResult<ArrayRef> {
    let mut chunks = Vec::new();
    let mut start = 0;
    while start < ROWS {
        let end = (start + WRITE_CHUNK).min(ROWS);
        chunks.push(build_chunk(start, end));
        start = end;
    }
    let dtype = chunks[0].dtype().clone();
    Ok(ChunkedArray::try_new(chunks, dtype)?.into_array())
}

/// Write the canonical file to `path`, creating parent directories as needed.
pub fn write_canonical(path: &Path) -> VortexResult<()> {
    let runtime = CurrentThreadRuntime::new();
    let session = VortexSession::default().with_handle(runtime.handle());
    let table = build_table()?;

    let mut bytes: Vec<u8> = Vec::new();
    runtime.block_on(async {
        session
            .write_options()
            .write(&mut bytes, table.to_array_stream())
            .await
    })?;

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| vortex_err!("failed to create {}: {e}", parent.display()))?;
    }
    std::fs::write(path, &bytes)
        .map_err(|e| vortex_err!("failed to write {}: {e}", path.display()))?;
    Ok(())
}

/// Write the canonical file only if it does not already exist (idempotent), so the bench and the
/// Gradle generator share one file rather than racing to overwrite it.
pub fn ensure_canonical(path: &Path) -> VortexResult<()> {
    let present = path.metadata().map(|m| m.len() > 0).unwrap_or(false);
    if present {
        return Ok(());
    }
    write_canonical(path)
}
