// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

package dev.vortex.bench;

import dev.vortex.api.DataSource;
import dev.vortex.api.Expression;
import dev.vortex.api.Scan;
import dev.vortex.api.ScanOptions;
import dev.vortex.api.Session;
import dev.vortex.jni.NativeLoader;
import dev.vortex.jni.NativeRuntime;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.apache.arrow.memory.BufferAllocator;
import org.apache.arrow.memory.RootAllocator;
import org.apache.arrow.vector.ipc.ArrowReader;
import org.apache.arrow.vector.types.pojo.Field;
import org.openjdk.jmh.annotations.Benchmark;
import org.openjdk.jmh.annotations.BenchmarkMode;
import org.openjdk.jmh.annotations.Fork;
import org.openjdk.jmh.annotations.Level;
import org.openjdk.jmh.annotations.Measurement;
import org.openjdk.jmh.annotations.Mode;
import org.openjdk.jmh.annotations.OperationsPerInvocation;
import org.openjdk.jmh.annotations.OutputTimeUnit;
import org.openjdk.jmh.annotations.Param;
import org.openjdk.jmh.annotations.Scope;
import org.openjdk.jmh.annotations.Setup;
import org.openjdk.jmh.annotations.State;
import org.openjdk.jmh.annotations.TearDown;
import org.openjdk.jmh.annotations.Threads;
import org.openjdk.jmh.annotations.Warmup;
import org.openjdk.jmh.infra.Blackhole;

/**
 * Measures read throughput through the vortex-jni boundary (JNI + the Arrow C Data Interface).
 *
 * <p>Every invocation scans the full {@link BenchData#ROWS}-row table, so {@code @OperationsPerInvocation(ROWS)} makes
 * JMH report <b>input rows scanned per second</b> directly. Each lane materializes the result batches and sums their
 * {@code getRowCount()} — no per-value work — so the numbers reflect scan + boundary cost rather than JVM-side
 * arithmetic. Vortex coalesces to ~64K-row read batches regardless of the writer's chunk size (see
 * {@link VortexJniBatchDiagnostic}), so boundary cost is amortized over large batches by construction.
 *
 * <ul>
 *   <li>{@code fullScan} — read all six columns.
 *   <li>{@code projection} — native projection of {@code id, y} (two of six columns).
 *   <li>{@code selectiveFilter} — native filter {@code cat = 'alpha'} (~1/16 selectivity).
 * </ul>
 *
 * <p>This reads a <b>shared canonical file</b> generated by the Rust side (see {@code BENCHMARKS.md} and the
 * {@code :vortex-jni:generateBenchFile} Gradle task), so these JMH {@code ops/s} are directly comparable to the Rust
 * {@code read_boundary} Divan bench reading the same bytes — the difference is the JNI + Arrow C Data boundary cost.
 * The Gradle {@code jmh} task passes the file path via the {@code -Dvortex.jni.bench.file} system property; running the
 * benchmark by hand requires setting it (or {@code VORTEX_JNI_BENCH_FILE}).
 */
@BenchmarkMode(Mode.Throughput)
@OutputTimeUnit(TimeUnit.SECONDS)
@OperationsPerInvocation(BenchData.ROWS)
@Warmup(iterations = 3, time = 2)
@Measurement(iterations = 5, time = 2)
@Fork(1)
@Threads(1)
@State(Scope.Benchmark)
public class VortexJniReadBenchmark {

    /** System property (set by the Gradle {@code jmh} task) pointing at the shared canonical {@code .vortex} file. */
    static final String BENCH_FILE_PROPERTY = "vortex.jni.bench.file";

    static final long EXPECTED_ALPHA_MATCHES = BenchData.ROWS / BenchData.CATS.length;

    /**
     * Background worker threads driving the JVM-wide pool: {@code 0} keeps the reading thread the only driver
     * (single-threaded), {@code -1} sizes the pool to the available parallelism so the scan's split tasks decode in
     * parallel in the background.
     */
    @Param({"0", "-1"})
    public int workerThreads;

    BufferAllocator allocator;
    Session session;
    DataSource dataSource;

    @Setup(Level.Trial)
    public void setup() throws Exception {
        NativeLoader.loadJni();
        if (workerThreads < 0) {
            NativeRuntime.setWorkerThreadsToAvailableParallelism();
        } else {
            NativeRuntime.setWorkerThreads(workerThreads);
        }
        allocator = new RootAllocator(Long.MAX_VALUE);
        session = Session.create();
        String uri = benchFile().toUri().toString();
        dataSource = DataSource.open(session, uri);
        validate();
    }

    /** Locate the shared canonical file (generated by {@code :vortex-jni:generateBenchFile}); fail loudly if absent. */
    private static Path benchFile() {
        String configured = System.getProperty(BENCH_FILE_PROPERTY);
        if (configured == null || configured.isBlank()) {
            configured = System.getenv("VORTEX_JNI_BENCH_FILE");
        }
        if (configured == null || configured.isBlank()) {
            throw new IllegalStateException("canonical bench file not configured: set -D" + BENCH_FILE_PROPERTY
                    + " (the Gradle `jmh` task does this). Run `./gradlew :vortex-jni:jmh`.");
        }
        Path path = Path.of(configured).toAbsolutePath();
        if (!Files.isRegularFile(path)) {
            throw new IllegalStateException("canonical bench file does not exist: " + path
                    + " — run `./gradlew :vortex-jni:generateBenchFile`.");
        }
        return path;
    }

    @TearDown(Level.Trial)
    public void teardown() {
        // The canonical file is shared with the Rust bench and managed by Gradle, so it is not deleted here.
        // Intentionally does not close the allocator either: DataSource/Scan native resources are released by
        // VortexCleaner at GC time, which races an explicit allocator.close() and trips leak detection. The JMH fork
        // exits after the trial and reclaims everything.
        dataSource = null;
    }

    /** Fail the trial loudly if the file or pushdown semantics are wrong — fast garbage must not be cited. */
    private void validate() throws Exception {
        if (!(dataSource.rowCount() instanceof DataSource.RowCount.Exact exact) || exact.value() != BenchData.ROWS) {
            throw new IllegalStateException(
                    "expected exactly " + BenchData.ROWS + " rows, got " + dataSource.rowCount());
        }
        // Native filter must return exactly ROWS/|CATS| rows for cat='alpha'.
        Expression filter = Expression.binary(
                Expression.BinaryOp.EQ, Expression.column("cat"), Expression.literal(BenchData.CATS[0]));
        long matched = 0;
        Scan scan = dataSource.scan(ScanOptions.builder().filter(filter).build());
        while (scan.hasNext()) {
            try (ArrowReader reader = scan.next().scanArrow(allocator)) {
                while (reader.loadNextBatch()) {
                    matched += reader.getVectorSchemaRoot().getRowCount();
                }
            }
        }
        if (matched != EXPECTED_ALPHA_MATCHES) {
            throw new IllegalStateException(
                    "filter cat='alpha' returned " + matched + ", expected " + EXPECTED_ALPHA_MATCHES);
        }
        // Native projection must yield exactly [id, y].
        Expression projection = Expression.select(new String[] {"id", "y"}, Expression.root());
        Scan pscan =
                dataSource.scan(ScanOptions.builder().projection(projection).build());
        if (pscan.hasNext()) {
            try (ArrowReader reader = pscan.next().scanArrow(allocator)) {
                if (reader.loadNextBatch()) {
                    List<String> names = reader.getVectorSchemaRoot().getSchema().getFields().stream()
                            .map(Field::getName)
                            .toList();
                    if (!names.equals(List.of("id", "y"))) {
                        throw new IllegalStateException("projection schema expected [id, y], got " + names);
                    }
                }
            }
        }
    }

    /** Full scan of all six columns. */
    @Benchmark
    public void fullScan(Blackhole bh) throws Exception {
        bh.consume(countRows(dataSource.scan(ScanOptions.of())));
    }

    /** Native projection pushdown: only id,y cross the boundary. */
    @Benchmark
    public void projection(Blackhole bh) throws Exception {
        Expression projection = Expression.select(new String[] {"id", "y"}, Expression.root());
        bh.consume(countRows(
                dataSource.scan(ScanOptions.builder().projection(projection).build())));
    }

    /** Native filter pushdown: only matching rows cross the boundary. */
    @Benchmark
    public void selectiveFilter(Blackhole bh) throws Exception {
        Expression filter = Expression.binary(
                Expression.BinaryOp.EQ, Expression.column("cat"), Expression.literal(BenchData.CATS[0]));
        bh.consume(
                countRows(dataSource.scan(ScanOptions.builder().filter(filter).build())));
    }

    /** Materialize every result batch and return the total row count — no per-value consumption. */
    private long countRows(Scan scan) throws Exception {
        long rows = 0;
        while (scan.hasNext()) {
            try (ArrowReader reader = scan.next().scanArrow(allocator)) {
                while (reader.loadNextBatch()) {
                    rows += reader.getVectorSchemaRoot().getRowCount();
                }
            }
        }
        return rows;
    }
}
