// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! FFI bindings to nvCOMP (generated by bindgen at build time).

include!(concat!(env!("OUT_DIR"), "/sys.rs"));
