# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401


class Array:
    r"""
    An array of zero or more *rows* each with the same set of *columns*.
    
    Examples
    --------
    
    Arrays support all the standard comparison operations:
    
        >>> import vortex as vx
        >>> a = vx.array(['dog', None, 'cat', 'mouse', 'fish'])
        >>> b = vx.array(['doug', 'jennifer', 'casper', 'mouse', 'faust'])
        >>> (a < b).to_arrow_array()
        <pyarrow.lib.BooleanArray object at ...>
        [
           true,
           null,
           false,
           false,
           false
        ]
        >>> (a <= b).to_arrow_array()
        <pyarrow.lib.BooleanArray object at ...>
        [
           true,
           null,
           false,
           true,
           false
        ]
        >>> (a == b).to_arrow_array()
        <pyarrow.lib.BooleanArray object at ...>
        [
           false,
           null,
           false,
           true,
           false
        ]
        >>> (a != b).to_arrow_array()
        <pyarrow.lib.BooleanArray object at ...>
        [
           true,
           null,
           true,
           false,
           true
        ]
        >>> (a >= b).to_arrow_array()
        <pyarrow.lib.BooleanArray object at ...>
        [
           false,
           null,
           true,
           true,
           true
        ]
        >>> (a > b).to_arrow_array()
        <pyarrow.lib.BooleanArray object at ...>
        [
           false,
           null,
           true,
           false,
           true
        ]
    """
    ...

