# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright the Vortex contributors

"""Build expressions for Vortex scans.

Scan binding currently supports field access, literals, binary operations, casts,
boolean negation, null tests, struct selection, and struct packing. Other
builders can construct expression nodes, but binding or serializing those
nodes raises an error until they have an authored binding rule.
"""

from ._lib.expr import (
    Expr,
    add,
    and_,
    and_collect,
    between,
    byte_length,
    case_when,
    cast,
    column,
    deserialize,
    div,
    eq,
    ext_storage,
    fill_null,
    get_item,
    gt,
    gt_eq,
    ilike,
    is_not_null,
    is_null,
    like,
    list_contains,
    list_length,
    list_sum,
    literal,
    lt,
    lt_eq,
    mask,
    merge,
    mul,
    not_,
    not_eq,
    not_ilike,
    not_like,
    or_,
    or_collect,
    pack,
    root,
    select,
    select_exclude,
    sub,
    variant_get,
    zip_,
)

__all__ = [
    "Expr",
    "add",
    "and_",
    "and_collect",
    "between",
    "byte_length",
    "case_when",
    "cast",
    "column",
    "deserialize",
    "div",
    "eq",
    "ext_storage",
    "fill_null",
    "get_item",
    "gt",
    "gt_eq",
    "ilike",
    "is_not_null",
    "is_null",
    "like",
    "list_contains",
    "list_length",
    "list_sum",
    "literal",
    "lt",
    "lt_eq",
    "mask",
    "merge",
    "mul",
    "not_",
    "not_eq",
    "not_ilike",
    "not_like",
    "or_",
    "or_collect",
    "pack",
    "root",
    "select",
    "select_exclude",
    "sub",
    "variant_get",
    "zip_",
]
