// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! Rust bindings to NVIDIA NVENC video encoder.
//!
//! This crate provides bindings to NVENC, with the library loaded at runtime
//! via `libloading`. This allows the crate to compile on systems without CUDA
//! or NVENC installed — the library is only required at runtime when the
//! functions are actually called.
//!
//! The NVENC library (`libnvidia-encode.so.1`) ships with the NVIDIA display
//! driver and does not require a separate SDK installation at runtime.
//!
//! # Platform Support
//!
//! NVENC is available on Linux and Windows with NVIDIA GPUs (Kepler+).
//! On other platforms, this crate still compiles but will fail at runtime
//! when trying to load the library.

use std::sync::OnceLock;

/// Raw FFI type definitions and dynamically-loaded function pointers from bindgen.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    unused_qualifications,
    unnecessary_transmutes,
    clippy::all,
    clippy::cast_possible_truncation
)]
pub mod sys;

// SAFETY: NvencLibrary contains only function pointers loaded from the shared
// library plus the libloading::Library handle. The raw `*mut _GUID` pointers
// in function pointer signatures don't affect thread safety — the library
// itself is safe to share across threads.
unsafe impl Send for sys::NvencLibrary {}
unsafe impl Sync for sys::NvencLibrary {}

pub mod encoder;
mod error;

pub use encoder::NvEncoder;
pub use error::NvencError;

// --- NVENC API version constants ---
// These are macros in the C header and not generated by bindgen.

/// NVENC API version: 12.2
pub const NVENCAPI_VERSION: u32 = sys::NVENCAPI_MAJOR_VERSION | (sys::NVENCAPI_MINOR_VERSION << 24);

/// Computes the versioned struct tag for NVENC API structs.
const fn nvencapi_struct_version(ver: u32) -> u32 {
    NVENCAPI_VERSION | (ver << 16) | (0x7 << 28)
}

/// Version tag for [`sys::NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS`].
pub const NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS_VER: u32 = nvencapi_struct_version(1);
/// Version tag for [`sys::NV_ENC_CONFIG`].
pub const NV_ENC_CONFIG_VER: u32 = nvencapi_struct_version(9) | (1 << 31);
/// Version tag for [`sys::NV_ENC_INITIALIZE_PARAMS`].
pub const NV_ENC_INITIALIZE_PARAMS_VER: u32 = nvencapi_struct_version(7) | (1 << 31);
/// Version tag for [`sys::NV_ENC_REGISTER_RESOURCE`].
pub const NV_ENC_REGISTER_RESOURCE_VER: u32 = nvencapi_struct_version(5);
/// Version tag for [`sys::NV_ENC_MAP_INPUT_RESOURCE`].
pub const NV_ENC_MAP_INPUT_RESOURCE_VER: u32 = nvencapi_struct_version(4);
/// Version tag for [`sys::NV_ENC_CREATE_BITSTREAM_BUFFER`].
pub const NV_ENC_CREATE_BITSTREAM_BUFFER_VER: u32 = nvencapi_struct_version(1);
/// Version tag for [`sys::NV_ENC_PIC_PARAMS`].
pub const NV_ENC_PIC_PARAMS_VER: u32 = nvencapi_struct_version(7) | (1 << 31);
/// Version tag for [`sys::NV_ENC_LOCK_BITSTREAM`].
pub const NV_ENC_LOCK_BITSTREAM_VER: u32 = nvencapi_struct_version(2) | (1 << 31);
/// Version tag for [`sys::NV_ENC_RC_PARAMS`].
pub const NV_ENC_RC_PARAMS_VER: u32 = nvencapi_struct_version(1);
/// Version tag for [`sys::NV_ENCODE_API_FUNCTION_LIST`].
pub const NV_ENCODE_API_FUNCTION_LIST_VER: u32 = nvencapi_struct_version(2);

// --- Well-known GUIDs ---
// These are `static const` in the C header and not generated by bindgen.

/// H.264 codec GUID.
pub const NV_ENC_CODEC_H264_GUID: sys::GUID = sys::GUID {
    Data1: 0x6BC8_2762,
    Data2: 0x4E63,
    Data3: 0x4ca4,
    Data4: [0xAA, 0x85, 0x1E, 0x50, 0xF3, 0x21, 0xF6, 0xBF],
};

/// Profile auto-select GUID.
pub const NV_ENC_CODEC_PROFILE_AUTOSELECT_GUID: sys::GUID = sys::GUID {
    Data1: 0xBFD6_F8E7,
    Data2: 0x233C,
    Data3: 0x4341,
    Data4: [0x8B, 0x3E, 0x48, 0x18, 0x52, 0x38, 0x03, 0xF4],
};

/// P4 preset GUID (balanced quality/speed).
pub const NV_ENC_PRESET_P4_GUID: sys::GUID = sys::GUID {
    Data1: 0xFC0A_8D3E,
    Data2: 0x45F8,
    Data3: 0x4CF8,
    Data4: [0x80, 0xC7, 0x29, 0x88, 0x71, 0x59, 0x0E, 0xBF],
};

/// P7 preset GUID (highest quality).
pub const NV_ENC_PRESET_P7_GUID: sys::GUID = sys::GUID {
    Data1: 0x8484_8C12,
    Data2: 0x6F71,
    Data3: 0x4C13,
    Data4: [0x93, 0x1B, 0x53, 0xE5, 0x5F, 0x52, 0x52, 0x0C],
};

/// The loaded NVENC library instance.
static NVENC_LIB: OnceLock<Result<sys::NvencLibrary, String>> = OnceLock::new();

fn load_nvenc() -> Result<sys::NvencLibrary, String> {
    let lib_name = if cfg!(target_os = "linux") {
        "libnvidia-encode.so.1"
    } else if cfg!(target_os = "windows") {
        "nvEncodeAPI64.dll"
    } else {
        return Err("NVENC is not supported on this platform".to_string());
    };

    // SAFETY: The NVENC library ships with the NVIDIA driver.
    unsafe {
        sys::NvencLibrary::new(lib_name)
            .map_err(|e| format!("Failed to load NVENC library ({lib_name}): {e}"))
    }
}

/// Gets a reference to the loaded NVENC library.
///
/// The library is loaded lazily on first access. Returns an error if the
/// library cannot be found or loaded.
pub fn nvenc_library() -> Result<&'static sys::NvencLibrary, NvencError> {
    NVENC_LIB
        .get_or_init(load_nvenc)
        .as_ref()
        .map_err(|e| NvencError::LibraryLoadError(e.clone()))
}
