// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! Generation of the published edition artifacts from the computed manifests.
//!
//! `cargo xtask generate-editions` calls [`generate`], which produces, under
//! `docs/specs/editions/`:
//!
//! 1. one JSON file per edition — the machine-readable definition;
//! 2. one Markdown page per edition, rendered *from the JSON file* so the published page and
//!    the machine-readable artifact cannot disagree;
//!
//! and rewrites the generated index block (table of editions plus the Sphinx toctree) inside
//! `docs/specs/editions.md` between the `editions:index` markers.

use std::fs;
use std::path::Path;

use crate::EditionError;
use crate::manifest::EditionManifest;
use crate::manifest::EditionStatus;
use crate::manifest::compute_manifests;

/// Marker opening the generated index block in `docs/specs/editions.md`.
pub const INDEX_BEGIN: &str = "<!-- editions:index:begin -->";
/// Marker closing the generated index block in `docs/specs/editions.md`.
pub const INDEX_END: &str = "<!-- editions:index:end -->";

/// Generate all edition artifacts under `repo_root`. Returns the paths written.
pub fn generate(repo_root: impl AsRef<Path>) -> Result<Vec<String>, EditionError> {
    let repo_root = repo_root.as_ref();
    let editions_dir = repo_root.join("docs/specs/editions");
    fs::create_dir_all(&editions_dir)
        .map_err(|e| EditionError::new(format!("creating {}: {e}", editions_dir.display())))?;

    let manifests = compute_manifests()?;
    let mut written = Vec::new();

    for manifest in &manifests {
        let json_path = editions_dir.join(format!("{}.json", manifest.id));
        let json = serde_json::to_string_pretty(manifest)
            .map_err(|e| EditionError::new(format!("serializing {}: {e}", manifest.id)))?;
        fs::write(&json_path, format!("{json}\n"))
            .map_err(|e| EditionError::new(format!("writing {}: {e}", json_path.display())))?;
        written.push(json_path.display().to_string());

        // Render the page from the JSON artifact, not the in-memory manifest, so the
        // published page and the machine-readable definition cannot disagree.
        let parsed: EditionManifest = serde_json::from_str(&json)
            .map_err(|e| EditionError::new(format!("re-parsing {}: {e}", manifest.id)))?;
        let md_path = editions_dir.join(format!("{}.md", manifest.id));
        fs::write(&md_path, render_edition_page(&parsed))
            .map_err(|e| EditionError::new(format!("writing {}: {e}", md_path.display())))?;
        written.push(md_path.display().to_string());
    }

    let index_path = repo_root.join("docs/specs/editions.md");
    splice_index(&index_path, &render_index(&manifests))?;
    written.push(index_path.display().to_string());

    Ok(written)
}

fn status_label(status: EditionStatus) -> &'static str {
    match status {
        EditionStatus::Draft => "draft",
        EditionStatus::Current => "current",
        EditionStatus::Superseded => "superseded",
    }
}

fn render_edition_page(manifest: &EditionManifest) -> String {
    let mut page = String::new();
    page.push_str(&format!(
        "<!-- Generated by `cargo xtask generate-editions` from {id}.json. Do not edit by \
         hand. -->\n\n# {id}\n\n",
        id = manifest.id
    ));

    if manifest.status == EditionStatus::Draft {
        page.push_str(&format!(
            ":::{{warning}}\n`{}` is a **draft**: it carries no compatibility guarantee, its \
             contents may change or be removed, and it cannot be targeted by the writer until \
             it is frozen.\n:::\n\n",
            manifest.id
        ));
    }

    page.push_str("| | |\n|---|---|\n");
    page.push_str(&format!(
        "| **Status** | {} |\n",
        status_label(manifest.status)
    ));
    page.push_str(&format!(
        "| **Frozen on** | {} |\n",
        manifest.frozen.as_deref().unwrap_or("—")
    ));
    let required_release = match (&manifest.required_vortex_release, manifest.status) {
        (Some(release), _) => release.as_str(),
        (None, EditionStatus::Draft) => "—",
        (None, _) => "the first release that includes this edition",
    };
    page.push_str(&format!(
        "| **Required Vortex release** | {required_release} |\n"
    ));
    page.push_str(&format!(
        "| **Supersedes** | {} |\n",
        manifest
            .supersedes
            .as_deref()
            .map(|s| format!("[{s}]({s}.md)"))
            .unwrap_or_else(|| "—".to_string())
    ));
    page.push_str(&format!(
        "| **Encodings** | {} |\n\n",
        manifest.encodings.len()
    ));

    page.push_str(&format!(
        "Machine-readable definition: {{download}}`{id}.json <{id}.json>`. See \
         [Editions](../editions.md) for what an edition guarantees.\n\n",
        id = manifest.id
    ));

    page.push_str("## Encodings\n\n");
    page.push_str("| Encoding ID | Since | Requires |\n|---|---|---|\n");
    for encoding in &manifest.encodings {
        page.push_str(&format!(
            "| `{}` | {} | {} |\n",
            encoding.id,
            encoding.since,
            encoding.required_vortex_release.as_deref().unwrap_or("—"),
        ));
    }
    page.push('\n');

    page.push_str("## Changes\n\n");
    let newly_added: Vec<&str> = manifest
        .encodings
        .iter()
        .filter(|e| e.since == manifest.id)
        .map(|e| e.id.as_str())
        .collect();
    match manifest.supersedes.as_deref() {
        None => {
            page.push_str(&format!(
                "First edition of the `{}` family — every encoding listed above is newly \
                 guaranteed.\n",
                manifest.family
            ));
        }
        Some(base) if newly_added.is_empty() => {
            page.push_str(&format!(
                "No changes relative to [{base}]({base}.md) yet.\n"
            ));
        }
        Some(base) => {
            page.push_str(&format!(
                "Relative to [{base}]({base}.md), added: {}.\n",
                newly_added
                    .iter()
                    .map(|id| format!("`{id}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
    }

    page
}

fn render_index(manifests: &[EditionManifest]) -> String {
    let mut index = String::new();
    index.push_str(INDEX_BEGIN);
    index.push_str(
        "\n<!-- Generated by `cargo xtask generate-editions`. Do not edit by hand. -->\n\n",
    );
    index.push_str("| Edition | Status | Frozen on | Encodings |\n|---|---|---|---|\n");
    for manifest in manifests {
        index.push_str(&format!(
            "| [{id}](editions/{id}.md) | {status} | {frozen} | {arrays} |\n",
            id = manifest.id,
            status = status_label(manifest.status),
            frozen = manifest.frozen.as_deref().unwrap_or("—"),
            arrays = manifest.encodings.len(),
        ));
    }
    index.push_str("\n```{toctree}\n---\nmaxdepth: 1\nhidden: true\n---\n\n");
    for manifest in manifests {
        index.push_str(&format!("editions/{}\n", manifest.id));
    }
    index.push_str("```\n");
    index.push_str(INDEX_END);
    index
}

fn splice_index(index_path: &Path, rendered: &str) -> Result<(), EditionError> {
    let content = fs::read_to_string(index_path)
        .map_err(|e| EditionError::new(format!("reading {}: {e}", index_path.display())))?;
    let start = content.find(INDEX_BEGIN).ok_or_else(|| {
        EditionError::new(format!(
            "{} does not contain the {INDEX_BEGIN} marker",
            index_path.display()
        ))
    })?;
    let end = content.find(INDEX_END).ok_or_else(|| {
        EditionError::new(format!(
            "{} does not contain the {INDEX_END} marker",
            index_path.display()
        ))
    })? + INDEX_END.len();
    if end <= start {
        return Err(EditionError::new(format!(
            "malformed editions index markers in {}",
            index_path.display()
        )));
    }
    let updated = format!("{}{}{}", &content[..start], rendered, &content[end..]);
    fs::write(index_path, updated)
        .map_err(|e| EditionError::new(format!("writing {}: {e}", index_path.display())))
}
