// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! The frozen-edition record under `vortex/editions`.
//!
//! A frozen edition carries a read-forever guarantee, so its encoding set must never change
//! again. Every frozen edition has one generated TOML file recording that contract: the
//! identifier, the minimum Vortex version whose reader supports it, and the full encoding
//! set. Freezing a new edition adds a file; nothing else may touch the directory, which CI
//! enforces by rejecting any diff that modifies or deletes an existing record
//! (`.github/scripts/check_frozen_editions.py`).
//!
//! The test here keeps the record honest in the other direction: the files must match what
//! [`super::EDITION_DECLARATIONS`] actually computes, so a frozen edition cannot drift
//! without the record drifting with it. Regenerate after freezing a new edition with:
//!
//! ```bash
//! UPDATE_FROZEN_EDITIONS=1 cargo test -p vortex --lib editions::frozen
//! ```
//!
//! [`vortex_edition::EditionInclusion::required_vortex_release`] is recorded in its own
//! table rather than beside each encoding, because it is the one fact here that is not fixed
//! at freeze time: it is backfilled from compat-fixture evidence as that evidence appears.
//! Keeping it in a table of its own makes a backfill purely an added line, so the record
//! stays append-only in the literal sense and CI can allow the fill-in while still rejecting
//! a change to a release that was already recorded.

use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::PathBuf;

use anyhow::Context;
use anyhow::anyhow;
use vortex_edition::Edition;
use vortex_edition::EditionError;
use vortex_edition::EditionSession;

use super::EDITION_DECLARATIONS;

/// Set to any value to rewrite the record instead of verifying it.
const UPDATE_VAR: &str = "UPDATE_FROZEN_EDITIONS";

const REGENERATE: &str = "UPDATE_FROZEN_EDITIONS=1 cargo test -p vortex --lib editions::frozen";

const HEADER: &str = "\
# Generated by `UPDATE_FROZEN_EDITIONS=1 cargo test -p vortex --lib editions::frozen`.
#
# This edition is frozen: it carries a read-forever guarantee, so this record of what it
# contains never changes again. Freezing a new edition adds a new file to this directory;
# editing or deleting an existing one is rejected by CI.";

fn record_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("editions")
}

fn session() -> Result<EditionSession, EditionError> {
    let session = EditionSession::empty();
    for declaration in EDITION_DECLARATIONS {
        session.declare(declaration)?;
    }
    Ok(session)
}

/// The frozen editions, paired with the version that freezing recorded. Drafts have no
/// record: a file appears in the directory at the moment an edition freezes.
fn frozen(session: &EditionSession) -> Vec<(Edition, &'static str)> {
    session
        .editions()
        .into_iter()
        .filter_map(|edition| edition.min_vortex_version.map(|version| (edition, version)))
        .collect()
}

/// Render one edition's record. Deterministic: both encoding lists are sorted by id, so the
/// generated bytes depend only on the declarations.
fn record(session: &EditionSession, edition: &Edition, min_vortex_version: &str) -> String {
    let inclusions = session.encodings_in(&edition.id);
    let members: BTreeSet<&str> = inclusions
        .iter()
        .map(|inclusion| inclusion.encoding_id.as_str())
        .collect();
    let added: BTreeSet<&str> = inclusions
        .iter()
        .filter(|inclusion| inclusion.since == edition.id)
        .map(|inclusion| inclusion.encoding_id.as_str())
        .collect();
    let releases: BTreeMap<&str, &str> = inclusions
        .iter()
        .filter_map(|inclusion| {
            inclusion
                .required_vortex_release
                .map(|release| (inclusion.encoding_id.as_str(), release))
        })
        .collect();

    let list = |ids: &BTreeSet<&str>| -> Vec<String> {
        ids.iter().map(|id| format!("    \"{id}\",")).collect()
    };

    let mut lines = vec![
        HEADER.to_string(),
        String::new(),
        format!("edition = \"{}\"", edition.id),
        format!("family = \"{}\"", edition.id.family),
        format!("min_vortex_version = \"{min_vortex_version}\""),
        String::new(),
        "# The encodings that join the family at this edition.".to_string(),
        "added = [".to_string(),
    ];
    lines.extend(list(&added));
    lines.extend([
        "]".to_string(),
        String::new(),
        "# The edition's full membership: the encodings above, plus every member of earlier"
            .to_string(),
        "# editions of the family.".to_string(),
        "encodings = [".to_string(),
    ]);
    lines.extend(list(&members));
    lines.extend([
        "]".to_string(),
        String::new(),
        "# The earliest Vortex release able to read each encoding, recorded from evidence as"
            .to_string(),
        "# that evidence appears. Unlike the rest of this file it is filled in after the"
            .to_string(),
        "# edition freezes, so entries are only ever added, never changed.".to_string(),
        "[required_vortex_release]".to_string(),
    ]);
    lines.extend(
        releases
            .iter()
            .map(|(id, release)| format!("\"{id}\" = \"{release}\"")),
    );
    lines.push(String::new());
    lines.join("\n")
}

fn record_path(dir: &std::path::Path, edition: &Edition) -> PathBuf {
    dir.join(format!("{}.toml", edition.id))
}

/// The `*.toml` file names present in the record directory.
fn existing_records(dir: &std::path::Path) -> anyhow::Result<BTreeSet<String>> {
    let mut names = BTreeSet::new();
    for entry in fs::read_dir(dir).with_context(|| format!("reading {}", dir.display()))? {
        let path = entry?.path();
        if path
            .extension()
            .is_some_and(|extension| extension == "toml")
            && let Some(name) = path.file_name().and_then(|name| name.to_str())
        {
            names.insert(name.to_string());
        }
    }
    Ok(names)
}

/// Every frozen edition has a record, every record matches the declarations exactly, and no
/// record exists without a frozen edition behind it.
///
/// The third check is what catches a frozen edition being deleted or unfrozen, so the update
/// mode deliberately never removes a file: unfreezing cannot be laundered through the
/// generator.
#[test]
fn records_match_the_frozen_editions() -> anyhow::Result<()> {
    let session = session()?;
    let dir = record_dir();
    let update = env::var_os(UPDATE_VAR).is_some();

    fs::create_dir_all(&dir).with_context(|| format!("creating {}", dir.display()))?;

    let mut expected_names = BTreeSet::new();
    for (edition, min_vortex_version) in frozen(&session) {
        let path = record_path(&dir, &edition);
        let expected = record(&session, &edition, min_vortex_version);
        expected_names.insert(format!("{}.toml", edition.id));

        let actual = match fs::read_to_string(&path) {
            Ok(actual) => Some(actual),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
            Err(error) => return Err(error).with_context(|| format!("reading {}", path.display())),
        };

        if actual.as_deref() == Some(expected.as_str()) {
            continue;
        }
        if update {
            fs::write(&path, &expected).with_context(|| format!("writing {}", path.display()))?;
            continue;
        }

        return Err(match actual {
            Some(_) => anyhow!(
                "the record of frozen edition {} no longer matches its declaration.\n\
                 A frozen edition's encodings are fixed forever: declare a new edition \
                 instead of changing this one.\n\
                 If you froze a new edition or recorded a required_vortex_release, \
                 regenerate with `{REGENERATE}`.\n\
                 Record: {}",
                edition.id,
                path.display(),
            ),
            None => anyhow!(
                "frozen edition {} has no record. Regenerate with `{REGENERATE}`.\n\
                 Expected: {}",
                edition.id,
                path.display(),
            ),
        });
    }

    let strays: Vec<String> = existing_records(&dir)?
        .difference(&expected_names)
        .cloned()
        .collect();
    if !strays.is_empty() {
        return Err(anyhow!(
            "{} has records with no frozen edition behind them: {strays:?}.\n\
             A frozen edition may never be deleted or returned to draft; its declaration must \
             stay in `EDITION_DECLARATIONS` with its `min_vortex_version` recorded.",
            dir.display(),
        ));
    }

    Ok(())
}
