// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! The edition records under `vortex/editions`.
//!
//! Every declared edition has one generated TOML file recording what it contains: the
//! identifier, the minimum Vortex version whose reader supports it once frozen, the full
//! encoding set, and the release recorded for each member.
//!
//! A record's mutability follows its edition. A draft is still being assembled, so its
//! record may change however the draft does. Freezing — recording a
//! [`vortex_edition::Edition::min_vortex_version`] — turns the record into a contract that
//! carries a read-forever guarantee, and from then on it may never change again. CI enforces
//! that by rejecting any diff that touches a record that was already frozen at the base
//! revision (`.github/scripts/check_edition_records.py`).
//!
//! The test here keeps the records honest in the other direction: they must match what
//! [`super::EDITION_DECLARATIONS`] actually computes, so an edition cannot drift without its
//! record drifting with it. Regenerate with:
//!
//! ```bash
//! UPDATE_EDITION_RECORDS=1 cargo test -p vortex --lib editions::records
//! ```
//!
//! [`vortex_edition::EditionInclusion::required_vortex_release`] sits in a table of its own
//! because it is the one part of a frozen record that is still allowed to move: it is an
//! upper bound recorded from the release current when the edition froze, refined as
//! compat-fixture evidence narrows it. Entries may be added or refined, never dropped.

use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::Path;
use std::path::PathBuf;

use anyhow::Context;
use anyhow::anyhow;
use vortex_edition::Edition;
use vortex_edition::EditionError;
use vortex_edition::EditionSession;

use super::EDITION_DECLARATIONS;

/// Set to any value to rewrite the records instead of verifying them.
const UPDATE_VAR: &str = "UPDATE_EDITION_RECORDS";

const REGENERATE: &str = "UPDATE_EDITION_RECORDS=1 cargo test -p vortex --lib editions::records";

const GENERATED_BY: &str =
    "# Generated by `UPDATE_EDITION_RECORDS=1 cargo test -p vortex --lib editions::records`.\n#";

const FROZEN_NOTE: &str = "\
# This edition is frozen: it carries a read-forever guarantee, so this record of what it
# contains never changes again. Freezing a new edition adds a new file to this directory;
# editing or deleting a frozen one is rejected by CI.";

const DRAFT_NOTE: &str = "\
# This edition is a draft: it carries no guarantee and is still being assembled, so this
# record changes with it. Recording a min_vortex_version freezes the edition, after which
# this file may never change again.";

fn record_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("editions")
}

fn session() -> Result<EditionSession, EditionError> {
    let session = EditionSession::empty();
    for declaration in EDITION_DECLARATIONS {
        session.declare(declaration)?;
    }
    Ok(session)
}

/// Render one edition's record. Deterministic: every list is sorted by encoding id, so the
/// generated bytes depend only on the declarations.
fn record(session: &EditionSession, edition: &Edition) -> String {
    let inclusions = session.encodings_in(&edition.id);
    let members: BTreeSet<&str> = inclusions
        .iter()
        .map(|inclusion| inclusion.encoding_id.as_str())
        .collect();
    let added: BTreeSet<&str> = inclusions
        .iter()
        .filter(|inclusion| inclusion.since == edition.id)
        .map(|inclusion| inclusion.encoding_id.as_str())
        .collect();
    let releases: BTreeMap<&str, &str> = inclusions
        .iter()
        .filter_map(|inclusion| {
            inclusion
                .required_vortex_release
                .map(|release| (inclusion.encoding_id.as_str(), release))
        })
        .collect();

    let list = |ids: &BTreeSet<&str>| -> Vec<String> {
        ids.iter().map(|id| format!("    \"{id}\",")).collect()
    };

    let note = if edition.is_draft() {
        DRAFT_NOTE
    } else {
        FROZEN_NOTE
    };
    let mut lines = vec![
        GENERATED_BY.to_string(),
        note.to_string(),
        String::new(),
        format!("edition = \"{}\"", edition.id),
        format!("family = \"{}\"", edition.id.family),
    ];
    if let Some(min_vortex_version) = edition.min_vortex_version {
        lines.push(format!("min_vortex_version = \"{min_vortex_version}\""));
    }
    lines.extend([
        String::new(),
        "# The encodings that join the family at this edition.".to_string(),
        "added = [".to_string(),
    ]);
    lines.extend(list(&added));
    lines.extend([
        "]".to_string(),
        String::new(),
        "# The edition's full membership: the encodings above, plus every member of earlier"
            .to_string(),
        "# editions of the family.".to_string(),
        "encodings = [".to_string(),
    ]);
    lines.extend(list(&members));
    lines.extend([
        "]".to_string(),
        String::new(),
        "# The earliest Vortex release able to read each encoding. Recorded as an upper bound"
            .to_string(),
        "# from the release current when the edition froze, and refined as compat-fixture"
            .to_string(),
        "# evidence narrows it, so entries are added or refined but never dropped.".to_string(),
        "[required_vortex_release]".to_string(),
    ]);
    lines.extend(
        releases
            .iter()
            .map(|(id, release)| format!("\"{id}\" = \"{release}\"")),
    );
    lines.push(String::new());
    lines.join("\n")
}

fn record_path(dir: &Path, edition: &Edition) -> PathBuf {
    dir.join(format!("{}.toml", edition.id))
}

/// The `*.toml` file names present in the record directory.
fn existing_records(dir: &Path) -> anyhow::Result<BTreeSet<String>> {
    let mut names = BTreeSet::new();
    for entry in fs::read_dir(dir).with_context(|| format!("reading {}", dir.display()))? {
        let path = entry?.path();
        if path
            .extension()
            .is_some_and(|extension| extension == "toml")
            && let Some(name) = path.file_name().and_then(|name| name.to_str())
        {
            names.insert(name.to_string());
        }
    }
    Ok(names)
}

/// A record carries a `min_vortex_version` exactly when the edition it records is frozen.
fn records_a_frozen_edition(contents: &str) -> bool {
    contents
        .lines()
        .any(|line| line.starts_with("min_vortex_version = "))
}

/// Every declared edition has a record, every record matches the declarations exactly, no
/// record exists without a declaration behind it, and no frozen edition is returned to draft.
///
/// The last two are what catch an edition being deleted or unfrozen, so the update mode
/// deliberately never removes a file and never unfreezes one: neither can be laundered
/// through the generator.
#[test]
fn records_match_the_declared_editions() -> anyhow::Result<()> {
    let session = session()?;
    let dir = record_dir();
    let update = env::var_os(UPDATE_VAR).is_some();

    fs::create_dir_all(&dir).with_context(|| format!("creating {}", dir.display()))?;

    let mut expected_names = BTreeSet::new();
    for edition in session.editions() {
        let path = record_path(&dir, &edition);
        let expected = record(&session, &edition);
        expected_names.insert(format!("{}.toml", edition.id));

        let actual = match fs::read_to_string(&path) {
            Ok(actual) => Some(actual),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => None,
            Err(error) => return Err(error).with_context(|| format!("reading {}", path.display())),
        };

        if let Some(actual) = &actual
            && edition.is_draft()
            && records_a_frozen_edition(actual)
        {
            return Err(anyhow!(
                "{} is recorded as frozen but its declaration is now a draft.\n\
                 Freezing is permanent: an edition that has recorded a min_vortex_version \
                 carries a read-forever guarantee and may never return to draft.",
                edition.id,
            ));
        }

        if actual.as_deref() == Some(expected.as_str()) {
            continue;
        }
        if update {
            fs::write(&path, &expected).with_context(|| format!("writing {}", path.display()))?;
            continue;
        }

        return Err(match actual {
            Some(_) => anyhow!(
                "the record of edition {} no longer matches its declaration.\n\
                 If {} is frozen its encodings are fixed forever: declare a new edition \
                 instead of changing this one.\n\
                 Otherwise regenerate with `{REGENERATE}`.\n\
                 Record: {}",
                edition.id,
                edition.id,
                path.display(),
            ),
            None => anyhow!(
                "edition {} has no record. Regenerate with `{REGENERATE}`.\n\
                 Expected: {}",
                edition.id,
                path.display(),
            ),
        });
    }

    let strays: Vec<String> = existing_records(&dir)?
        .difference(&expected_names)
        .cloned()
        .collect();
    if !strays.is_empty() {
        return Err(anyhow!(
            "{} has records with no declared edition behind them: {strays:?}.\n\
             A frozen edition may never be deleted; its declaration must stay in \
             `EDITION_DECLARATIONS`.",
            dir.display(),
        ));
    }

    Ok(())
}
