# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright the Vortex contributors

"""Resolve declarative benchmark definitions into GitHub Actions matrices.

The benchmarks and profiles that CI runs are intentionally kept out of this implementation module.
Edit :mod:`bench_orchestrator.benchmarks` to change them.

There are three independent axes, and every difference between CI jobs lives in exactly one place:

* **Target composition** -- each :class:`BenchmarkDef` declares its canonical target set once, as a
  delta from the shared :data:`STANDARD` core (opt in with ``| df(...)`` or restrict with
  ``.only(...)``).
* **Selection** -- a :class:`Profile` picks the benchmarks for one CI schedule.
* **Target policy** -- a :class:`Profile` narrows each selected benchmark's declared targets
  (:func:`all_targets` for full coverage, :func:`defaults` for the cheap PR/nightly lane).

The resolver turns ``(profile)`` into the GitHub Actions ``include:`` array. A workflow consumes it
with the standard dynamic-matrix pattern::

    plan:
      outputs: {matrix: "${{ steps.p.outputs.matrix }}"}
      steps:
        - id: p
          run: echo "matrix=$(uv run vx-bench matrix ${{ inputs.profile }})" >> "$GITHUB_OUTPUT"
    bench:
      needs: plan
      strategy:
        matrix:
          include: ${{ fromJSON(needs.plan.outputs.matrix) }}

Run ``vx-bench matrix <profile> --pretty`` locally to preview exactly what a job will run.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable
from dataclasses import dataclass
from enum import Enum

from .config import Benchmark, BenchmarkTarget, Engine, Format


class Storage(Enum):
    """Where a benchmark's data lives when it runs."""

    NVME = "nvme"
    S3 = "s3"

    @property
    def label(self) -> str:
        """Human-facing name used in benchmark display names (e.g. ``TPC-H SF=1 on NVME``)."""
        return "NVME" if self is Storage.NVME else "S3"


def _dedupe(targets: Iterable[BenchmarkTarget]) -> tuple[BenchmarkTarget, ...]:
    """Normalize and de-duplicate targets, preserving first-seen order."""
    return tuple(dict.fromkeys(target.normalized() for target in targets))


@dataclass(frozen=True)
class TargetSet:
    """An ordered, de-duplicated set of engine/format targets with small algebra.

    Supports ``|`` (union / opt-in) and :meth:`only` (restrict to engines) so a benchmark can
    express its targets as a delta from a shared default.
    """

    targets: tuple[BenchmarkTarget, ...] = ()

    def __post_init__(self) -> None:
        object.__setattr__(self, "targets", _dedupe(self.targets))

    def __or__(self, other: TargetSet) -> TargetSet:
        """Return the union of two target sets (opt in to more targets)."""
        return TargetSet(self.targets + other.targets)

    def only(self, *engines: Engine) -> TargetSet:
        """Restrict to targets whose engine is one of ``engines``."""
        keep = set(engines)
        return TargetSet(tuple(target for target in self.targets if target.engine in keep))

    def formats(self) -> list[Format]:
        """Return the distinct formats referenced by these targets, in first-seen order."""
        return list(dict.fromkeys(target.format for target in self.targets))

    def __iter__(self):
        return iter(self.targets)

    def __len__(self) -> int:
        return len(self.targets)


def targets(engine: Engine, *formats: Format) -> TargetSet:
    """Build a :class:`TargetSet` for one engine across several formats."""
    return TargetSet(tuple(BenchmarkTarget(engine=engine, format=fmt) for fmt in formats))


def df(*formats: Format) -> TargetSet:
    """Shortcut for DataFusion targets across ``formats``."""
    return targets(Engine.DATAFUSION, *formats)


def duck(*formats: Format) -> TargetSet:
    """Shortcut for DuckDB targets across ``formats``."""
    return targets(Engine.DUCKDB, *formats)


#: The columnar comparison core shared by almost every SQL benchmark: both engines across the
#: three headline Vortex/Parquet formats. Benchmarks opt in to extras (arrow, lance, duckdb).
STANDARD = df(Format.PARQUET, Format.VORTEX, Format.VORTEX_COMPACT) | duck(
    Format.PARQUET, Format.VORTEX, Format.VORTEX_COMPACT
)

#: The cheap default lane used for pull requests and nightly: two engines, two headline formats.
DEFAULTS = df(Format.PARQUET, Format.VORTEX) | duck(Format.PARQUET, Format.VORTEX)

# arrow is an in-memory format and lance data is produced by the lance backend itself, so neither
# is generated by the data-gen step. Everything else in a benchmark's targets needs data prepared.
_NOT_GENERATED = frozenset({Format.ARROW, Format.LANCE})

# Canonical ordering for the generated `data_formats` list, so emitted matrices are stable.
_FORMAT_ORDER = (
    Format.ARROW,
    Format.PARQUET,
    Format.VORTEX,
    Format.VORTEX_COMPACT,
    Format.VORTEX_NATIVE,
    Format.DUCKDB,
    Format.LANCE,
)


@dataclass(frozen=True)
class BenchmarkDef:
    """A single benchmark and the canonical set of targets it runs.

    The declared ``targets`` are the *superset* this benchmark cares about (its intent). Profiles
    narrow this set via a target policy; they never add targets a benchmark did not declare.
    """

    id: str
    benchmark: Benchmark
    name: str
    targets: TargetSet
    storage: Storage = Storage.NVME
    scale_factor: float | int | None = None
    iterations: int | None = None
    nightly: bool = False
    local_dir: str | None = None
    remote_key: str | None = None

    @property
    def subcommand(self) -> str:
        """The ``vx-bench`` subcommand for this benchmark (its benchmark enum value)."""
        return self.benchmark.value


# A target policy maps a benchmark's declared targets to the targets a profile actually runs.
TargetPolicy = Callable[[BenchmarkDef], TargetSet]


def all_targets(benchmark: BenchmarkDef) -> TargetSet:
    """Target policy: run every target the benchmark declared."""
    return benchmark.targets


def defaults(benchmark: BenchmarkDef) -> TargetSet:
    """Target policy: keep only the default lane (datafusion,duckdb × parquet,vortex).

    This intersects the default lane with the benchmark's declared targets, so a benchmark that
    only supports a subset (e.g. duckdb-only) still runs a sensible default.
    """
    engines = {Engine.DATAFUSION, Engine.DUCKDB}
    formats = {Format.PARQUET, Format.VORTEX}
    return TargetSet(tuple(t for t in benchmark.targets if t.engine in engines and t.format in formats))


@dataclass(frozen=True)
class Profile:
    """A named CI benchmark configuration: which benchmarks, and how many targets each runs."""

    nightly: bool = False
    targets: TargetPolicy = all_targets
    description: str = ""


def _valid_for_storage(target_set: TargetSet, storage: Storage) -> TargetSet:
    """Drop targets that are invalid for the given storage (lance has no remote reader)."""
    if storage is Storage.S3:
        return TargetSet(tuple(t for t in target_set if t.format is not Format.LANCE))
    return target_set


def _data_formats(target_set: TargetSet) -> list[Format]:
    """Formats the data-gen step must produce for these targets, in canonical order."""
    present = set(target_set.formats())
    return [fmt for fmt in _FORMAT_ORDER if fmt in present and fmt not in _NOT_GENERATED]


def _scale_string(scale_factor: float | int) -> str:
    """Render a scale factor exactly as declared for ``--opt scale-factor``."""
    return str(scale_factor)


def _matrix_entry(benchmark: BenchmarkDef, run_targets: TargetSet) -> dict[str, object]:
    """Build one GitHub Actions ``include:`` entry for a resolved benchmark."""
    entry: dict[str, object] = {
        "id": benchmark.id,
        "subcommand": benchmark.subcommand,
        "name": benchmark.name,
        "targets": [t.to_dict() for t in run_targets],
        "data_formats": [fmt.value for fmt in _data_formats(run_targets)],
    }
    if benchmark.scale_factor is not None:
        entry["scale_factor"] = _scale_string(benchmark.scale_factor)
    if benchmark.iterations is not None:
        entry["iterations"] = str(benchmark.iterations)
    if benchmark.local_dir is not None:
        entry["local_dir"] = benchmark.local_dir
    if benchmark.remote_key is not None:
        entry["remote_key"] = benchmark.remote_key
    return entry


def resolve_matrix(profile: Profile, benchmarks: Iterable[BenchmarkDef]) -> list[dict[str, object]]:
    """Resolve ``profile`` and ``benchmarks`` into GitHub Actions matrix entries."""
    entries: list[dict[str, object]] = []
    for benchmark in benchmarks:
        if benchmark.nightly != profile.nightly:
            continue
        run_targets = _valid_for_storage(profile.targets(benchmark), benchmark.storage)
        if not run_targets:
            continue
        entries.append(_matrix_entry(benchmark, run_targets))
    return entries
