// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! Regenerates the Rust bindings for the Protocol Buffers schemas owned by the Vortex crates.
//!
//! Every workspace member with a `proto` directory owns the `.proto` schemas under it, and gets
//! their bindings checked in under `src/proto/generated/`. Schemas are parsed by `protox` and
//! generated by `prost-build`, both pure Rust, so regeneration needs no `protoc` and its output is
//! pinned by `Cargo.lock`. CI regenerates the bindings and fails when the checked-in copies differ.

use std::fs;
use std::path::Path;
use std::path::PathBuf;

use anyhow::Context;
use anyhow::bail;

use crate::workspace::collect_with_extension;
use crate::workspace::schema_owners;

/// Directory under each crate root holding its schemas.
const SCHEMA_DIR: &str = "proto";

/// `@generated` keeps `cargo fmt` off the file (`format_generated_files = false`).
const HEADER: &str = "\
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors
//
// @generated by `cargo run -p xtask -- generate-proto`, do not modify.

";

pub fn generate_proto() -> anyhow::Result<()> {
    let owners = schema_owners(SCHEMA_DIR, "proto")?;
    if owners.is_empty() {
        bail!("no `<crate>/proto/**/*.proto` schemas found among the workspace members");
    }
    // Schemas import other crates' schemas by their path under that crate's `proto` directory,
    // so every crate's directory is an include root.
    let includes = owners
        .iter()
        .map(|owner| owner.crate_dir.join(SCHEMA_DIR))
        .collect::<Vec<_>>();

    for owner in &owners {
        let out_dir = owner
            .crate_dir
            .join("src")
            .join(SCHEMA_DIR)
            .join("generated");
        fs::create_dir_all(&out_dir)
            .with_context(|| format!("failed to create {}", out_dir.display()))?;
        let generated = generate_into(&owner.schemas, &includes, &out_dir)?;
        for path in generated {
            let code = fs::read_to_string(&path)
                .with_context(|| format!("failed to read {}", path.display()))?;
            fs::write(&path, format!("{HEADER}{code}"))
                .with_context(|| format!("failed to write {}", path.display()))?;
            println!("wrote {}", path.display());
        }
    }
    Ok(())
}

/// Compiles `schemas` into `out_dir`, returning the files `prost-build` wrote there.
fn generate_into(
    schemas: &[PathBuf],
    includes: &[PathBuf],
    out_dir: &Path,
) -> anyhow::Result<Vec<PathBuf>> {
    let file_descriptors =
        protox::compile(schemas, includes).context("failed to compile protos")?;

    // prost-build names its output after the package, so clear the directory first to drop
    // bindings for packages that no longer exist.
    fs::remove_dir_all(out_dir)
        .with_context(|| format!("failed to clear {}", out_dir.display()))?;
    fs::create_dir_all(out_dir)
        .with_context(|| format!("failed to create {}", out_dir.display()))?;

    prost_build::Config::new()
        .out_dir(out_dir)
        .compile_fds(file_descriptors)
        .context("failed to generate proto bindings")?;

    let mut generated = Vec::new();
    collect_with_extension(out_dir, "rs", &mut generated)?;
    generated.sort();
    Ok(generated)
}
