// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! Export the edition records under `vortex/editions`.
//!
//! Every declared edition gets one TOML file recording what it contains: the identifier, the
//! minimum Vortex version whose reader supports it once frozen, and its full encoding set.
//!
//! A record's mutability follows its edition. A draft is still being assembled, so its record
//! changes with it. Freezing — recording a `min_vortex_version` — turns the record into a
//! contract carrying a read-forever guarantee, and from then on it may never change again. CI
//! enforces that against git history in `.github/scripts/check_edition_records.py`; this
//! exporter enforces the two rules that history cannot see, refusing to delete a record or to
//! unfreeze one.

use std::collections::BTreeSet;
use std::fs;
use std::path::Path;
use std::path::PathBuf;

use anyhow::Context;
use anyhow::anyhow;
use vortex::editions::EDITION_DECLARATIONS;
use vortex::editions::Edition;
use vortex::editions::EditionSession;

const GENERATED_BY: &str = "# Generated by `cargo run -p xtask -- generate-editions`.\n#";

const FROZEN_NOTE: &str = "\
# This edition is frozen: it carries a read-forever guarantee, so this record of what it
# contains never changes again. Freezing a new edition adds a new file to this directory;
# editing or deleting a frozen one is rejected by CI.";

const DRAFT_NOTE: &str = "\
# This edition is a draft: it carries no guarantee and is still being assembled, so this
# record changes with it. Recording a min_vortex_version freezes the edition, after which
# this file may never change again.";

/// Render one edition's record. Deterministic: every list is sorted by encoding id, so the
/// generated bytes depend only on the declarations.
fn record(session: &EditionSession, edition: &Edition) -> String {
    let inclusions = session.encodings_in(&edition.id);
    let members: BTreeSet<&str> = inclusions
        .iter()
        .map(|inclusion| inclusion.encoding_id.as_str())
        .collect();
    let added: BTreeSet<&str> = inclusions
        .iter()
        .filter(|inclusion| inclusion.since == edition.id)
        .map(|inclusion| inclusion.encoding_id.as_str())
        .collect();

    let list = |ids: &BTreeSet<&str>| -> Vec<String> {
        ids.iter().map(|id| format!("    \"{id}\",")).collect()
    };

    let note = if edition.is_draft() {
        DRAFT_NOTE
    } else {
        FROZEN_NOTE
    };
    let mut lines = vec![
        GENERATED_BY.to_string(),
        note.to_string(),
        String::new(),
        format!("edition = \"{}\"", edition.id),
        format!("family = \"{}\"", edition.id.family),
    ];
    if let Some(min_vortex_version) = edition.min_vortex_version {
        lines.push(format!("min_vortex_version = \"{min_vortex_version}\""));
    }
    lines.extend([
        String::new(),
        "# The encodings that join the family at this edition.".to_string(),
        "added = [".to_string(),
    ]);
    lines.extend(list(&added));
    lines.extend([
        "]".to_string(),
        String::new(),
        "# The edition's full membership: the encodings above, plus every member of earlier"
            .to_string(),
        "# editions of the family.".to_string(),
        "encodings = [".to_string(),
    ]);
    lines.extend(list(&members));
    lines.extend(["]".to_string(), String::new()]);
    lines.join("\n")
}

/// The `*.toml` file names present in the record directory.
fn existing_records(dir: &Path) -> anyhow::Result<BTreeSet<String>> {
    let mut names = BTreeSet::new();
    for entry in fs::read_dir(dir).with_context(|| format!("reading {}", dir.display()))? {
        let path = entry?.path();
        if path
            .extension()
            .is_some_and(|extension| extension == "toml")
            && let Some(name) = path.file_name().and_then(|name| name.to_str())
        {
            names.insert(name.to_string());
        }
    }
    Ok(names)
}

/// A record carries a `min_vortex_version` exactly when the edition it records is frozen.
fn records_a_frozen_edition(contents: &str) -> bool {
    contents
        .lines()
        .any(|line| line.starts_with("min_vortex_version = "))
}

pub fn generate_editions() -> anyhow::Result<()> {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../vortex/editions");
    fs::create_dir_all(&dir).with_context(|| format!("creating {}", dir.display()))?;

    let session = EditionSession::empty();
    for declaration in EDITION_DECLARATIONS {
        session
            .declare(declaration)
            .map_err(|error| anyhow!("declaring editions: {error}"))?;
    }
    session
        .validate()
        .map_err(|error| anyhow!("validating editions: {error}"))?;

    let mut expected = BTreeSet::new();
    for edition in session.editions() {
        let path = dir.join(format!("{}.toml", edition.id));
        expected.insert(format!("{}.toml", edition.id));

        // Freezing is permanent, and the record on disk is the only memory of it. Refusing
        // here means unfreezing cannot be laundered through the exporter.
        if edition.is_draft()
            && let Ok(previous) = fs::read_to_string(&path)
            && records_a_frozen_edition(&previous)
        {
            return Err(anyhow!(
                "{} is recorded as frozen but its declaration is now a draft.\n\
                 An edition that recorded a min_vortex_version carries a read-forever \
                 guarantee and may never return to draft.",
                edition.id,
            ));
        }

        fs::write(&path, record(&session, &edition))
            .with_context(|| format!("writing {}", path.display()))?;
    }

    let strays: Vec<String> = existing_records(&dir)?
        .difference(&expected)
        .cloned()
        .collect();
    if !strays.is_empty() {
        return Err(anyhow!(
            "{} has records with no declared edition behind them: {strays:?}.\n\
             A frozen edition may never be deleted; its declaration must stay in \
             `EDITION_DECLARATIONS`.",
            dir.display(),
        ));
    }

    Ok(())
}
