// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! Seeded random fixture sweep.
//!
//! Where the curated fixtures each target one encoding, the sweep writes many files from
//! randomly generated arrays so that old readers see dtypes, nullability, nesting, lengths and
//! encoding combinations nobody thought to curate. Every file is deterministic in its seed, so a
//! failure can be regenerated by name.
//!
//! For each seed the sweep writes:
//!
//! - `sweep_<seed>_canonical.vortex`: a random canonical array through the flat layout.
//! - `sweep_<seed>_btrblocks.vortex`: the same array through the default compressor and layout
//!   strategy (chunked, struct, zoned and dict layouts, zone-map aggregates).
//! - `sweep_<seed>_compact.vortex`: the same through the compact compressor.
//! - `sweep_<seed>_dict.vortex`, `sweep_<seed>_constant.vortex`, `sweep_<seed>_runend.vortex`:
//!   randomly built encoded arrays through the flat layout.
//!
//! A write the target edition rejects is reported and skipped rather than failing the sweep.

use std::path::Path;
use std::sync::Arc;

use arbitrary::Arbitrary;
use arbitrary::Unstructured;
use serde::Serialize;
use vortex::compressor::BtrBlocksCompressorBuilder;
use vortex::file::WriteStrategyBuilder;
use vortex::layout::LayoutStrategy;
use vortex::layout::layouts::flat::writer::FlatLayoutStrategy;
use vortex_array::ArrayRef;
use vortex_array::IntoArray;
use vortex_array::arrays::StructArray;
use vortex_array::arrays::arbitrary::ArbitraryArray;
use vortex_array::arrays::arbitrary::ArbitraryArrayConfig;
use vortex_array::arrays::arbitrary::ArbitraryWith;
use vortex_array::arrays::constant::ArbitraryConstantArray;
use vortex_array::arrays::dict::ArbitraryDictArray;
use vortex_array::dtype::DType;
use vortex_array::dtype::FieldNames;
use vortex_array::dtype::Nullability;
use vortex_array::validity::Validity;
use vortex_error::VortexResult;
use vortex_error::vortex_err;
use vortex_runend::ArbitraryRunEndArray;

use crate::adapter;

/// Bytes of entropy handed to `arbitrary` per generated array.
const ENTROPY_BYTES: usize = 1 << 16;

#[derive(Serialize)]
struct SweepFile {
    name: String,
    seed: u64,
    kind: &'static str,
}

#[derive(Serialize)]
struct SkippedFile {
    name: String,
    seed: u64,
    kind: &'static str,
    error: String,
}

#[derive(Serialize)]
struct SweepJson {
    written: Vec<SweepFile>,
    skipped: Vec<SkippedFile>,
}

/// SplitMix64, so the sweep needs no RNG dependency and a seed reproduces its bytes anywhere.
fn entropy(seed: u64) -> Vec<u8> {
    let mut state = seed.wrapping_add(0x9E37_79B9_7F4A_7C15);
    let mut out = Vec::with_capacity(ENTROPY_BYTES);
    while out.len() < ENTROPY_BYTES {
        state = state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^= z >> 31;
        out.extend_from_slice(&z.to_le_bytes());
    }
    out
}

/// Files hold a non-nullable struct at the top level, so wrap anything else in a single-field
/// struct.
fn as_struct(array: ArrayRef) -> VortexResult<ArrayRef> {
    if matches!(array.dtype(), DType::Struct(_, Nullability::NonNullable)) {
        return Ok(array);
    }
    let len = array.len();
    Ok(StructArray::try_new(
        FieldNames::from(["value"]),
        vec![array],
        len,
        Validity::NonNullable,
    )?
    .into_array())
}

fn random_canonical(u: &mut Unstructured<'_>, max_len: usize) -> VortexResult<ArrayRef> {
    let array = ArbitraryArray::arbitrary_with_config(
        u,
        &ArbitraryArrayConfig {
            dtype: None,
            len: 0..=max_len,
        },
    )
    .map_err(|e| vortex_err!("arbitrary: {e}"))?;
    as_struct(array.0)
}

fn random_encoded(u: &mut Unstructured<'_>, kind: &str) -> VortexResult<ArrayRef> {
    let array = match kind {
        "dict" => ArbitraryDictArray::arbitrary(u)
            .map_err(|e| vortex_err!("arbitrary: {e}"))?
            .0
            .into_array(),
        "constant" => ArbitraryConstantArray::arbitrary(u)
            .map_err(|e| vortex_err!("arbitrary: {e}"))?
            .0
            .into_array(),
        "runend" => ArbitraryRunEndArray::arbitrary(u)
            .map_err(|e| vortex_err!("arbitrary: {e}"))?
            .0
            .into_array(),
        other => return Err(vortex_err!("unknown encoded kind {other}")),
    };
    as_struct(array)
}

fn compressed_strategy(compact: bool) -> Arc<dyn LayoutStrategy> {
    let session = adapter::session();
    let mut compressor = BtrBlocksCompressorBuilder::from_session(&session);
    if compact {
        compressor = compressor.with_compact();
    }
    WriteStrategyBuilder::from_session(&session)
        .with_btrblocks_builder(compressor)
        .build()
}

/// Write `count` seeds' worth of sweep files, starting at `first_seed`, into `output_dir`.
pub fn sweep(
    output_dir: &Path,
    first_seed: u64,
    count: u64,
    max_len: usize,
) -> VortexResult<()> {
    std::fs::create_dir_all(output_dir)
        .map_err(|e| vortex_err!("failed to create output dir: {e}"))?;

    let mut json = SweepJson {
        written: Vec::new(),
        skipped: Vec::new(),
    };

    for seed in first_seed..first_seed + count {
        let bytes = entropy(seed);
        let mut u = Unstructured::new(&bytes);

        let mut jobs: Vec<(&'static str, VortexResult<ArrayRef>, Arc<dyn LayoutStrategy>)> =
            Vec::new();
        match random_canonical(&mut u, max_len) {
            Ok(array) => {
                jobs.push((
                    "canonical",
                    Ok(array.clone()),
                    Arc::new(FlatLayoutStrategy::default()),
                ));
                jobs.push(("btrblocks", Ok(array.clone()), compressed_strategy(false)));
                jobs.push(("compact", Ok(array), compressed_strategy(true)));
            }
            Err(e) => jobs.push(("canonical", Err(e), Arc::new(FlatLayoutStrategy::default()))),
        }
        for kind in ["dict", "constant", "runend"] {
            jobs.push((
                kind,
                random_encoded(&mut u, kind),
                Arc::new(FlatLayoutStrategy::default()),
            ));
        }

        for (kind, array, strategy) in jobs {
            let name = format!("sweep_{seed}_{kind}.vortex");
            let path = output_dir.join(&name);
            // A writer panic on one random array must not end the sweep: record it as a skip.
            let result = array.and_then(|array| {
                std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                    adapter::write_compressed(&path, array, strategy)
                }))
                .unwrap_or_else(|panic| {
                    let msg = panic
                        .downcast_ref::<String>()
                        .cloned()
                        .or_else(|| panic.downcast_ref::<&str>().map(|s| s.to_string()))
                        .unwrap_or_else(|| "unknown panic".to_string());
                    Err(vortex_err!("writer panicked: {msg}"))
                })
            });
            match result {
                Ok(()) => {
                    eprintln!("  wrote {name}");
                    json.written.push(SweepFile { name, seed, kind });
                }
                Err(e) => {
                    eprintln!("  skip {name}: {e}");
                    drop(std::fs::remove_file(&path));
                    json.skipped.push(SkippedFile {
                        name,
                        seed,
                        kind,
                        error: e.to_string(),
                    });
                }
            }
        }
    }

    let text = serde_json::to_string_pretty(&json)
        .map_err(|e| vortex_err!("failed to serialize sweep.json: {e}"))?;
    std::fs::write(output_dir.join("sweep.json"), format!("{text}\n"))
        .map_err(|e| vortex_err!("failed to write sweep.json: {e}"))?;
    eprintln!(
        "\ndone: {} files written, {} skipped, in {}",
        json.written.len(),
        json.skipped.len(),
        output_dir.display()
    );
    Ok(())
}
