// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! Seeded random fixture sweep.
//!
//! Where the curated fixtures each target one encoding, the sweep writes many files from
//! randomly generated arrays so that old readers see dtypes, nullability, nesting, lengths,
//! offsets and encoding combinations nobody thought to curate. Every file is deterministic in
//! its seed, so a failure can be regenerated by name.
//!
//! For each seed the sweep writes:
//!
//! - `sweep_<seed>_canonical.vortex`: a random canonical array through the flat layout.
//! - `sweep_<seed>_sliced.vortex`: a random slice of that array, so offsets are non-zero.
//! - `sweep_<seed>_btrblocks.vortex` and `sweep_<seed>_compact.vortex`: the array through the
//!   default and compact compressor pipelines, with randomised row block size and data block
//!   target, so files have many zones and chunks.
//! - `sweep_<seed>_encoded.vortex`: columns of random base arrays (integers, floats, strings,
//!   booleans, timestamps, decimals) each run through a random stack of encoders, then maybe
//!   sliced.
//! - `sweep_<seed>_dict.vortex`, `sweep_<seed>_constant.vortex`, `sweep_<seed>_runend.vortex`:
//!   randomly built encoded arrays through the flat layout.
//!
//! Each written file also gets a set of read-path queries in `queries.json`. A write the target
//! edition rejects, or that panics the writer, is reported and skipped.

use std::path::Path;
use std::sync::Arc;

use arbitrary::Arbitrary;
use arbitrary::Unstructured;
use serde::Serialize;
use vortex::compressor::BtrBlocksCompressorBuilder;
use vortex::encodings::alp::RDEncoder;
use vortex::encodings::alp::RDEncoderExt;
use vortex::encodings::alp::alp_encode;
use vortex::encodings::datetime_parts::DateTimeParts;
use vortex::encodings::datetime_parts::split_temporal;
use vortex::encodings::decimal_byte_parts::DecimalByteParts;
use vortex::encodings::fastlanes::FoR;
use vortex::encodings::fastlanes::RLE;
use vortex::encodings::fsst::fsst_compress;
use vortex::encodings::fsst::fsst_train_compressor;
use vortex::encodings::pco::Pco;
use vortex::encodings::runend::RunEnd;
use vortex::encodings::runend::compress::runend_encode;
use vortex::encodings::sequence::Sequence;
use vortex::encodings::sparse::Sparse;
use vortex::encodings::zigzag::zigzag_encode;
use vortex::encodings::zstd::Zstd;
use vortex::file::WriteStrategyBuilder;
use vortex::layout::LayoutStrategy;
use vortex::layout::layouts::flat::writer::FlatLayoutStrategy;
use vortex_array::ArrayRef;
use vortex_array::Canonical;
use vortex_array::ExecutionCtx;
use vortex_array::IntoArray;
use vortex_array::VortexSessionExecute;
use vortex_array::arrays::PrimitiveArray;
use vortex_array::arrays::primitive::PrimitiveArrayExt;
use vortex_array::arrays::StructArray;
use vortex_array::arrays::TemporalArray;
use vortex_array::arrays::VarBinViewArray;
use vortex_array::arrays::arbitrary::ArbitraryArray;
use vortex_array::arrays::arbitrary::ArbitraryArrayConfig;
use vortex_array::arrays::arbitrary::ArbitraryWith;
use vortex_array::arrays::constant::ArbitraryConstantArray;
use vortex_array::arrays::dict::ArbitraryDictArray;
use vortex_array::builders::dict::dict_encode;
use vortex_array::dtype::DType;
use vortex_array::dtype::DecimalDType;
use vortex_array::dtype::FieldName;
use vortex_array::dtype::FieldNames;
use vortex_array::dtype::Nullability;
use vortex_array::dtype::PType;
use vortex_array::extension::datetime::TimeUnit;
use vortex_array::validity::Validity;
use vortex_buffer::Buffer;
use vortex_error::VortexResult;
use vortex_error::vortex_err;
use vortex_runend::ArbitraryRunEndArray;

use crate::adapter;
use crate::queries;
use crate::queries::QueryFile;

/// Bytes of entropy handed to `arbitrary` per seed.
const ENTROPY_BYTES: usize = 1 << 17;

#[derive(Serialize)]
struct SweepFile {
    name: String,
    seed: u64,
    kind: &'static str,
}

#[derive(Serialize)]
struct SkippedFile {
    name: String,
    seed: u64,
    kind: &'static str,
    error: String,
}

#[derive(Serialize)]
struct SweepJson {
    written: Vec<SweepFile>,
    skipped: Vec<SkippedFile>,
}

/// SplitMix64, so the sweep needs no RNG dependency and a seed reproduces its bytes anywhere.
fn entropy(seed: u64) -> Vec<u8> {
    let mut state = seed.wrapping_add(0x9E37_79B9_7F4A_7C15);
    let mut out = Vec::with_capacity(ENTROPY_BYTES);
    while out.len() < ENTROPY_BYTES {
        state = state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^= z >> 31;
        out.extend_from_slice(&z.to_le_bytes());
    }
    out
}

fn bad(e: arbitrary::Error) -> vortex_error::VortexError {
    vortex_err!("arbitrary: {e}")
}

/// Run a generator or writer step, turning a panic into an error so one random input cannot end
/// the sweep. The panic is still a finding, so its message is kept.
fn catching<T>(what: &str, f: impl FnOnce() -> VortexResult<T>) -> VortexResult<T> {
    std::panic::catch_unwind(std::panic::AssertUnwindSafe(f)).unwrap_or_else(|panic| {
        let msg = panic
            .downcast_ref::<String>()
            .cloned()
            .or_else(|| panic.downcast_ref::<&str>().map(|s| s.to_string()))
            .unwrap_or_else(|| "unknown panic".to_string());
        Err(vortex_err!("{what} panicked: {msg}"))
    })
}

/// Files hold a non-nullable struct at the top level, so wrap anything else in a single-field
/// struct.
fn as_struct(array: ArrayRef) -> VortexResult<ArrayRef> {
    if matches!(array.dtype(), DType::Struct(_, Nullability::NonNullable)) {
        return Ok(array);
    }
    let len = array.len();
    Ok(StructArray::try_new(
        FieldNames::from(["value"]),
        vec![array],
        len,
        Validity::NonNullable,
    )?
    .into_array())
}

fn random_canonical(u: &mut Unstructured<'_>, max_len: usize) -> VortexResult<ArrayRef> {
    let array = ArbitraryArray::arbitrary_with_config(
        u,
        &ArbitraryArrayConfig {
            dtype: None,
            len: 0..=max_len,
        },
    )
    .map_err(bad)?;
    as_struct(array.0)
}

/// A random, single-chunk canonical array of exactly `dtype` and `len`.
fn random_typed(
    u: &mut Unstructured<'_>,
    dtype: DType,
    len: usize,
    ctx: &mut ExecutionCtx,
) -> VortexResult<Canonical> {
    let array = ArbitraryArray::arbitrary_with_config(
        u,
        &ArbitraryArrayConfig {
            dtype: Some(dtype),
            len: len..=len,
        },
    )
    .map_err(bad)?
    .0;
    array.execute::<Canonical>(ctx)
}

/// A random slice of the array, canonicalized because a lazy slice cannot be serialized. The
/// result still has lengths and buffer offsets the generator would not otherwise produce.
fn random_slice(
    u: &mut Unstructured<'_>,
    array: ArrayRef,
    ctx: &mut ExecutionCtx,
) -> VortexResult<ArrayRef> {
    let len = array.len();
    if len < 2 {
        return Ok(array);
    }
    let start = u.int_in_range(0..=len - 1).map_err(bad)?;
    let end = u.int_in_range(start..=len).map_err(bad)?;
    as_struct(array.slice(start..end)?.execute::<Canonical>(ctx)?.into_array())
}

/// A random i64 array built from i32 values, so timestamps and decimals stay in range.
fn random_i64_from_i32(
    u: &mut Unstructured<'_>,
    nullability: Nullability,
    len: usize,
    ctx: &mut ExecutionCtx,
) -> VortexResult<PrimitiveArray> {
    let Canonical::Primitive(p) =
        random_typed(u, DType::Primitive(PType::I32, nullability), len, ctx)?
    else {
        return Err(vortex_err!("expected primitive"));
    };
    let validity = p.validity()?;
    let values: Buffer<i64> = p.as_slice::<i32>().iter().map(|v| i64::from(*v)).collect();
    Ok(PrimitiveArray::new(values, validity))
}

/// Apply one random encoder to a primitive array. An encoder that declines the input leaves the
/// array canonical, so the sweep never fails on an inapplicable choice.
fn encode_primitive(
    u: &mut Unstructured<'_>,
    p: PrimitiveArray,
    ctx: &mut ExecutionCtx,
) -> VortexResult<ArrayRef> {
    let ptype = p.ptype();
    let mut options: Vec<&str> = vec!["zstd", "rle", "sparse", "dict", "runend", "none"];
    if !matches!(ptype, PType::U8 | PType::I8) {
        options.push("pco");
    }
    if ptype.is_int() {
        options.extend(["for", "zigzag"]);
    }
    if matches!(ptype, PType::F32 | PType::F64) {
        options.push("alp");
    }
    if ptype == PType::F64 {
        options.push("alprd");
    }
    let choice = *u.choose(&options).map_err(bad)?;
    let canonical = p.clone().into_array();
    let encoded: VortexResult<ArrayRef> = catching(&format!("encoder {choice}"), || match choice {
        "for" => FoR::encode(p, ctx).map(|a| a.into_array()),
        "zigzag" => zigzag_encode(p.as_view()).map(|a| a.into_array()),
        "alp" => alp_encode(p.as_view(), None, ctx).map(|a| a.into_array()),
        "alprd" => Ok(RDEncoder::new::<f64>(p.as_slice::<f64>())
            .encode(p.as_view())
            .into_array()),
        "pco" => Pco::from_primitive(p.as_view(), 8, 0, ctx).map(|a| a.into_array()),
        "zstd" => Zstd::from_primitive(&p, 3, 128, ctx).map(|a| a.into_array()),
        "rle" => RLE::encode(p.as_view(), ctx).map(|a| a.into_array()),
        "sparse" => Sparse::encode(&canonical, None, ctx),
        "dict" => dict_encode(&canonical, ctx).map(|a| a.into_array()),
        "runend" => {
            let (ends, values) = runend_encode(p.as_view(), ctx);
            RunEnd::try_new(ends.into_array(), values, ctx).map(|a| a.into_array())
        }
        _ => Ok(canonical.clone()),
    });
    Ok(encoded.unwrap_or_else(|e| {
        eprintln!("  (encoder {choice} declined {ptype}: {e})");
        canonical
    }))
}

fn encode_strings(
    u: &mut Unstructured<'_>,
    v: VarBinViewArray,
    ctx: &mut ExecutionCtx,
) -> VortexResult<ArrayRef> {
    let canonical = v.clone().into_array();
    let choice = *u
        .choose(&["fsst", "zstd", "dict", "sparse", "none"])
        .map_err(bad)?;
    let encoded: VortexResult<ArrayRef> = catching(&format!("encoder {choice}"), || match choice {
        "fsst" => fsst_train_compressor(&canonical, ctx)
            .and_then(|c| fsst_compress(&canonical, &c, ctx))
            .map(|a| a.into_array()),
        "zstd" => Zstd::from_var_bin_view(&v, 3, 128, ctx).map(|a| a.into_array()),
        "dict" => dict_encode(&canonical, ctx).map(|a| a.into_array()),
        "sparse" => Sparse::encode(&canonical, None, ctx),
        _ => Ok(canonical.clone()),
    });
    Ok(encoded.unwrap_or_else(|e| {
        eprintln!("  (encoder {choice} declined utf8: {e})");
        canonical
    }))
}

fn encode_generic(
    u: &mut Unstructured<'_>,
    array: ArrayRef,
    ctx: &mut ExecutionCtx,
) -> VortexResult<ArrayRef> {
    let choice = *u.choose(&["dict", "sparse", "none"]).map_err(bad)?;
    let encoded: VortexResult<ArrayRef> = catching(&format!("encoder {choice}"), || match choice {
        "dict" => dict_encode(&array, ctx).map(|a| a.into_array()),
        "sparse" => Sparse::encode(&array, None, ctx),
        _ => Ok(array.clone()),
    });
    Ok(encoded.unwrap_or_else(|e| {
        eprintln!("  (encoder {choice} declined {}: {e})", array.dtype());
        array
    }))
}

/// One random column: a random base array of the chosen kind through a random encoder.
fn random_encoded_column(
    u: &mut Unstructured<'_>,
    len: usize,
    ctx: &mut ExecutionCtx,
) -> VortexResult<ArrayRef> {
    let nullability: Nullability = u.arbitrary().map_err(bad)?;
    let kind = *u
        .choose(&[
            "uint",
            "int",
            "float",
            "utf8",
            "bool",
            "timestamp",
            "decimal",
            "sequence",
        ])
        .map_err(bad)?;
    match kind {
        "uint" | "int" | "float" => {
            let ptype = *match kind {
                "uint" => u.choose(&[PType::U8, PType::U16, PType::U32, PType::U64]),
                "int" => u.choose(&[PType::I8, PType::I16, PType::I32, PType::I64]),
                _ => u.choose(&[PType::F32, PType::F64]),
            }
            .map_err(bad)?;
            let Canonical::Primitive(p) =
                random_typed(u, DType::Primitive(ptype, nullability), len, ctx)?
            else {
                return Err(vortex_err!("expected primitive"));
            };
            encode_primitive(u, p, ctx)
        }
        "utf8" => {
            let Canonical::VarBinView(v) = random_typed(u, DType::Utf8(nullability), len, ctx)?
            else {
                return Err(vortex_err!("expected strings"));
            };
            encode_strings(u, v, ctx)
        }
        "bool" => {
            let array = random_typed(u, DType::Bool(nullability), len, ctx)?.into_array();
            encode_generic(u, array, ctx)
        }
        "timestamp" => {
            let p = random_i64_from_i32(u, nullability, len, ctx)?;
            let unit = *u
                .choose(&[
                    TimeUnit::Seconds,
                    TimeUnit::Milliseconds,
                    TimeUnit::Microseconds,
                    TimeUnit::Nanoseconds,
                ])
                .map_err(bad)?;
            let tz = (*u.choose(&[None, Some("UTC"), Some("Europe/London")]).map_err(bad)?)
                .map(Arc::<str>::from);
            let temporal = TemporalArray::new_timestamp(p.into_array(), unit, tz);
            if u.arbitrary().map_err(bad)? {
                let dtype = temporal.dtype().clone();
                let parts = split_temporal(temporal, ctx)?;
                Ok(DateTimeParts::try_new(dtype, parts.days, parts.seconds, parts.subseconds)?
                    .into_array())
            } else {
                Ok(temporal.into_array())
            }
        }
        "decimal" => {
            let p = random_i64_from_i32(u, nullability, len, ctx)?;
            let precision = u.int_in_range(10..=18).map_err(bad)?;
            let scale = u.int_in_range(-5..=10).map_err(bad)?;
            Ok(DecimalByteParts::try_new(p.into_array(), DecimalDType::new(precision, scale))?
                .into_array())
        }
        _ => {
            let base: i64 = u.int_in_range(-1000..=1000).map_err(bad)?;
            let step: i64 = u.int_in_range(-7..=7).map_err(bad)?;
            Ok(Sequence::try_new_typed::<i64>(base, step, nullability, len)?.into_array())
        }
    }
}

fn random_encoded_tree(
    u: &mut Unstructured<'_>,
    max_len: usize,
    ctx: &mut ExecutionCtx,
) -> VortexResult<ArrayRef> {
    let len = u.int_in_range(0..=max_len).map_err(bad)?;
    let ncols = u.int_in_range(1..=5).map_err(bad)?;
    let mut names = Vec::new();
    let mut columns = Vec::new();
    for i in 0..ncols {
        names.push(format!("c{i}"));
        columns.push(random_encoded_column(u, len, ctx)?);
    }
    let array = StructArray::try_new(
        FieldNames::from_iter(names.iter().map(|n| FieldName::from(n.as_str()))),
        columns,
        len,
        Validity::NonNullable,
    )?
    .into_array();
    Ok(array)
}

fn random_encoded(u: &mut Unstructured<'_>, kind: &str) -> VortexResult<ArrayRef> {
    let array = match kind {
        "dict" => ArbitraryDictArray::arbitrary(u).map_err(bad)?.0.into_array(),
        "constant" => ArbitraryConstantArray::arbitrary(u)
            .map_err(bad)?
            .0
            .into_array(),
        "runend" => ArbitraryRunEndArray::arbitrary(u)
            .map_err(bad)?
            .0
            .into_array(),
        other => return Err(vortex_err!("unknown encoded kind {other}")),
    };
    as_struct(array)
}

/// The default write strategy with a randomised row block size and data block target, so files
/// vary in how many zones and chunks they have.
fn compressed_strategy(
    u: &mut Unstructured<'_>,
    compact: bool,
) -> VortexResult<Arc<dyn LayoutStrategy>> {
    let session = adapter::session();
    let mut compressor = BtrBlocksCompressorBuilder::from_session(&session);
    if compact {
        compressor = compressor.with_compact();
    }
    let mut builder = WriteStrategyBuilder::from_session(&session).with_btrblocks_builder(compressor);
    if let Some(rows) = *u.choose(&[None, Some(64), Some(512), Some(2048)]).map_err(bad)? {
        builder = builder.with_row_block_size(rows);
    }
    if let Some(bytes) = *u
        .choose(&[None, Some(1u64 << 10), Some(1u64 << 16)])
        .map_err(bad)?
    {
        builder = builder.with_data_block_target_bytes(Some(bytes));
    }
    Ok(builder.build())
}

fn flat() -> Arc<dyn LayoutStrategy> {
    Arc::new(FlatLayoutStrategy::default())
}

/// Write `count` seeds' worth of sweep files, starting at `first_seed`, into `output_dir`.
pub fn sweep(
    output_dir: &Path,
    first_seed: u64,
    count: u64,
    max_len: usize,
) -> VortexResult<()> {
    std::fs::create_dir_all(output_dir)
        .map_err(|e| vortex_err!("failed to create output dir: {e}"))?;

    let session = adapter::session();
    let mut ctx = session.create_execution_ctx();
    let mut json = SweepJson {
        written: Vec::new(),
        skipped: Vec::new(),
    };
    let mut queries = QueryFile::new();

    for seed in first_seed..first_seed + count {
        let bytes = entropy(seed);
        let mut u = Unstructured::new(&bytes);

        let mut jobs: Vec<(&'static str, VortexResult<ArrayRef>, Arc<dyn LayoutStrategy>)> =
            Vec::new();
        match catching("generator", || random_canonical(&mut u, max_len)) {
            Ok(array) => {
                jobs.push(("canonical", Ok(array.clone()), flat()));
                let sliced = catching("generator", || random_slice(&mut u, array.clone(), &mut ctx));
                jobs.push(("sliced", sliced, compressed_strategy(&mut u, false)?));
                jobs.push((
                    "btrblocks",
                    Ok(array.clone()),
                    compressed_strategy(&mut u, false)?,
                ));
                jobs.push(("compact", Ok(array), compressed_strategy(&mut u, true)?));
            }
            Err(e) => jobs.push(("canonical", Err(e), flat())),
        }
        let encoded = catching("generator", || random_encoded_tree(&mut u, max_len, &mut ctx));
        jobs.push(("encoded", encoded, flat()));
        for kind in ["dict", "constant", "runend"] {
            let array = catching("generator", || random_encoded(&mut u, kind));
            jobs.push((kind, array, flat()));
        }

        for (kind, array, strategy) in jobs {
            let name = format!("sweep_{seed}_{kind}.vortex");
            let path = output_dir.join(&name);
            // A writer panic on one random array must not end the sweep: record it as a skip.
            let result = array.and_then(|array| {
                catching("writer", || {
                    adapter::write_compressed(&path, array.clone(), strategy).map(|()| array)
                })
            });
            match result {
                Ok(array) => {
                    eprintln!("  wrote {name}");
                    match catching("query generator", || queries::generate(&array, &mut u, &mut ctx)) {
                        Ok(qs) if !qs.is_empty() => {
                            queries.insert(name.clone(), qs);
                        }
                        Ok(_) => {}
                        Err(e) => eprintln!("  (no queries for {name}: {e})"),
                    }
                    json.written.push(SweepFile { name, seed, kind });
                }
                Err(e) => {
                    eprintln!("  skip {name}: {e}");
                    drop(std::fs::remove_file(&path));
                    json.skipped.push(SkippedFile {
                        name,
                        seed,
                        kind,
                        error: e.to_string(),
                    });
                }
            }
        }
    }

    let text = serde_json::to_string_pretty(&json)
        .map_err(|e| vortex_err!("failed to serialize sweep.json: {e}"))?;
    std::fs::write(output_dir.join("sweep.json"), format!("{text}\n"))
        .map_err(|e| vortex_err!("failed to write sweep.json: {e}"))?;
    let text = serde_json::to_string(&queries)
        .map_err(|e| vortex_err!("failed to serialize queries: {e}"))?;
    std::fs::write(output_dir.join(queries::QUERIES_FILE), format!("{text}\n"))
        .map_err(|e| vortex_err!("failed to write queries: {e}"))?;
    eprintln!(
        "\ndone: {} files written, {} skipped, {} files with queries, in {}",
        json.written.len(),
        json.skipped.len(),
        queries.len(),
        output_dir.display()
    );
    Ok(())
}
