// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! FFI bindings for ClickHouse.
//!
//! This module is auto-generated by bindgen when ClickHouse headers are available.
//! For now, it contains placeholder definitions.

#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]

// Placeholder types - will be replaced by bindgen-generated code
// when ClickHouse headers are available.

/// Result status for operations.
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum vortex_ch_state {
    Success = 0,
    Error = 1,
}
