name: Benchmarks

on:
  push:
    branches: [ develop ]

permissions:
  id-token: write  # enables AWS-GitHub OIDC
  actions: read
  contents: write
  deployments: write

jobs:
  commit-metadata:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::375504701696:role/GitHubBenchmarkRole
          aws-region: us-east-1
      - name: Upload Commit Metadata
        shell: bash
        run: |
          set -Eeu -o pipefail -x

          sudo apt-get update && sudo apt-get install -y jq
          bash scripts/commit-json.sh > new-commit.json
          bash scripts/cat-s3.sh vortex-benchmark-results-database commits.json new-commit.json

  bench:
    timeout-minutes: 120
    runs-on:
      - runs-on=${{ github.run_id }}
      - family=c6id.8xlarge
      - image=ubuntu24-full-x64
      - spot=false
      - extras=s3-cache
      - tag=${{ matrix.benchmark.id }}
    strategy:
      matrix:
        benchmark:
          - id: random_access
            name: Random Access
          - id: compress
            name: Compression
    steps:
      - uses: runs-on/action@v2
        with:
          sccache: s3

      # TODO(robert): Remove this once we update the ami
      - name: Manually mount tracefs and debugfs
        run: |
          sudo mount -t debugfs none /sys/kernel/debug
          sudo mount -t tracefs nodev /sys/kernel/tracing
          sudo mount -t tracefs nodev /sys/kernel/debug/tracing

      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-rust

      - name: Install DuckDB
        run: |
          wget -qO- https://github.com/duckdb/duckdb/releases/download/v1.3.2/duckdb_cli-linux-amd64.zip | funzip > duckdb
          chmod +x duckdb
          echo "$PWD" >> $GITHUB_PATH

      - name: Build binary
        shell: bash
        env:
          RUSTFLAGS: '-C target-cpu=native -C force-frame-pointers=yes'
        run: |
          cargo build --bin ${{ matrix.benchmark.id }} --package bench-vortex --profile release_debug

      - name: Setup Polar Signals
        uses: polarsignals/gh-actions-ps-profiling@v0.4.0
        with:
          polarsignals_cloud_token: ${{ secrets.POLAR_SIGNALS_API_KEY }}
          labels: 'branch=${{ github.ref_name }};gh_run_id=${{ github.run_id }};benchmark=${{ matrix.benchmark.id }}'
          profiling_frequency: 200

      - name: Run ${{ matrix.benchmark.name }} benchmark
        shell: bash
        env:
          RUST_BACKTRACE: full
        run: |
          target/release_debug/${{ matrix.benchmark.id }} -d gh-json -o ${{ matrix.benchmark.id }}.json

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::375504701696:role/GitHubBenchmarkRole
          aws-region: us-east-1

      - name: Upload Benchmark Results
        shell: bash
        run: |
          bash scripts/cat-s3.sh vortex-benchmark-results-database data.json.gz ${{ matrix.benchmark.id }}.json
  sql:
    uses: ./.github/workflows/sql-benchmarks.yml
    secrets: inherit
    with:
      mode: 'develop'
