name: CI / Java

# Concurrency control:
# - PRs: new commits on a feature branch will cancel in-progress (outdated) runs.
# - Push to develop: runs queue sequentially, never cancelled.
# - `workflow_dispatch`: groups by branch and queues if run on develop.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}
on:
  push:
    branches: [develop]
  pull_request: { }
  workflow_dispatch: { }

permissions:
  actions: read
  contents: read

env:
  CARGO_TERM_COLOR: auto
  RUST_BACKTRACE: 1

jobs:
  build-java:
    name: "Java"
    runs-on: >-
      ${{ github.repository == 'vortex-data/vortex'
          && format('runs-on={0}/runner=amd64-medium/image=ubuntu24-full-x64-pre-v2/tag=java', github.run_id)
          || 'ubuntu-latest' }}
    timeout-minutes: 40
    steps:
      - uses: runs-on/action@v2
        if: github.repository == 'vortex-data/vortex'
        with:
          sccache: s3
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-prebuild
      - run: ./gradlew test --parallel
        working-directory: ./java

  check-java-publish-build:
    runs-on: ${{ matrix.target.runs-on }}
    container:
      image: "ubuntu:20.04"
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        target:
          - { os: ubuntu, runs-on: "ubuntu-24.04-arm", target: aarch64-unknown-linux-gnu }
          - { os: ubuntu, runs-on: "ubuntu-24.04", target: x86_64-unknown-linux-gnu }
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare-java-linux
      - uses: actions/setup-java@v5
        with:
          distribution: "corretto"
          java-version: "17"
      - uses: ./.github/actions/setup-rust
        with:
          targets: ${{ matrix.target.target }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          enable-sccache: "false"
      - run: cargo build --package vortex-jni
