name: Compat Test

on:
  schedule:
    - cron: "0 6 * * 1"  # Monday 6am UTC
  workflow_dispatch: {}

jobs:
  compat-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run compat tests
        run: >
          python vortex-test/compat-gen/scripts/compat.py check
