name: Nightly Benchmarks

concurrency:
  # The group causes runs to queue instead of running in parallel.
  group: nightly-bench
  # This queues manual triggers to run after scheduled benchmarks complete.
  cancel-in-progress: false

on:
  schedule:
    - cron: "0 0 * * *"  # daily
  workflow_dispatch: { }

permissions:
  id-token: write  # enables AWS-GitHub OIDC
  actions: read
  contents: write

jobs:
  sql:
    uses: ./.github/workflows/sql-bench-matrix.yml
    secrets:
      POLAR_SIGNALS_API_KEY: ${{ secrets.POLAR_SIGNALS_API_KEY }}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
      OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
      BENCH_REVALIDATE_TOKEN: ${{ secrets.BENCH_REVALIDATE_TOKEN }}
      INCIDENT_IO_ALERT_TOKEN: ${{ secrets.INCIDENT_IO_ALERT_TOKEN }}
    with:
      mode: "develop"
      machine_type: ${{ matrix.machine_type.instance_name }}
      matrix_preset: "nightly"
    strategy:
      # A single run not should kill the others
      fail-fast: false
      matrix:
        machine_type:
          - id: x86
            instance_name: c6id.metal
