name: Release Drafter

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    # Permits a custom run to create a pre-release
    inputs:
      prerelease-identifier:
        description: "RC identifier (e.g., rc, beta, alpha)"
        type: string
        default: "rc"

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: release-drafter/release-drafter@563bf132657a13ded0b01fcb723c5a58cdd824e2  # v7.2.1
        with:
          commitish: ${{ github.ref_name }}
          prerelease: ${{ github.event_name == 'workflow_dispatch' }}
          prerelease-identifier: ${{ inputs.prerelease-identifier || '' }}
