name: Test MacOS

on:
  push:
    branches:
      - adamg/test-macos

jobs:
    build-arm: 
        runs-on: macos-13
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/cleanup
            - uses: ./.github/actions/setup-rust
            - name: rust-toolchain
              shell: bash
              run: echo "version=$(cat rust-toolchain.toml | grep channel | awk -F'\"' '{print $2}')" >> $GITHUB_OUTPUT
            - name: Disable SCCACHE Config  # Doesn't work with cross-compilation
              shell: bash
              run: echo "RUSTC_WRAPPER=" >> $GITHUB_ENV
            - name: Build wheels - aarch64
              uses: PyO3/maturin-action@v1
              with:
                rust-toolchain: ${{ steps.rust-toolchain.version }}
                working-directory: pyvortex
                target: aarch64
                args: --release --interpreter python3.10
