name: Test MacOS

on:
  push:
    branches:
      - adamg/test-macos

jobs:
    build-arm: 
        runs-on: macos-13-arm64
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/cleanup
            - uses: ./.github/actions/setup-rust
            - uses: spiraldb/actions/.github/actions/setup-uv@0.2.0
            - name: rust-toolchain
              shell: bash
              run: echo "version=$(cat rust-toolchain.toml | grep channel | awk -F'\"' '{print $2}')" >> $GITHUB_OUTPUT
            # - name: Build wheels - x86_64
            #   uses: PyO3/maturin-action@v1
            #   with:
            #     rust-toolchain: ${{ steps.rust-toolchain.version }}
            #     working-directory: pyvortex
            #     target: x86_64
            #     args: --release --interpreter python3.10 --sdist
            - name: Build wheels - aarch64
              uses: PyO3/maturin-action@v1
              with:
                rust-toolchain: ${{ steps.rust-toolchain.version }}
                working-directory: pyvortex
                target: aarch64  # NB: aarch64 becomes arm64 in the wheel's platform tag.
                args: --release --interpreter python3.10