// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright the Vortex contributors

//! Generates Rust FFI bindings for NVIDIA NVENC video encoder.
//!
//! Bindings are generated unconditionally from a vendored nvEncodeAPI.h header.
//! The library (`libnvidia-encode.so.1`) ships with the NVIDIA driver and is
//! loaded at runtime via libloading.

#![expect(clippy::unwrap_used)]
#![expect(clippy::expect_used)]

use std::env;
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let include_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("include");
    println!("cargo:rerun-if-changed={}", include_dir.display());

    let bindings = bindgen::Builder::default()
        .header(include_dir.join("nvEncodeAPI.h").to_string_lossy())
        .clang_arg(format!("-I{}", include_dir.display()))
        // Only load the two exported entry points via libloading.
        // The actual encoder functions come through the NV_ENCODE_API_FUNCTION_LIST.
        .allowlist_function("NvEncodeAPICreateInstance")
        .allowlist_function("NvEncodeAPIGetMaxSupportedVersion")
        // Include all NVENC types
        .allowlist_type("NVENCSTATUS")
        .allowlist_type("GUID")
        .allowlist_type("NV_ENC_.*")
        .allowlist_type("NV_ENCODE_API_FUNCTION_LIST")
        // Include #define constants (version numbers, flags).
        // Do NOT allowlist NV_ENC_.* vars — the official header declares GUIDs as
        // `static const GUID`, which dynamic_library_name would try to load from
        // the shared library at runtime. We define GUIDs manually in lib.rs.
        .allowlist_var("NVENCAPI_.*")
        .allowlist_var("NV_ENC_PIC_FLAG_.*")
        .allowlist_var("NV_MAX_SEQ_HDR_LEN")
        .allowlist_var("NVENC_INFINITE_GOPLENGTH")
        .dynamic_library_name("NvencLibrary")
        .dynamic_link_require_all(true)
        .wrap_unsafe_ops(true)
        // The official header uses `typedef enum _FOO { ... } FOO;` with leading
        // underscores on the underlying enum names. Disable enum name prepending
        // so constants are named e.g. `NV_ENC_SUCCESS` not `_NVENCSTATUS_NV_ENC_SUCCESS`.
        .prepend_enum_name(false)
        .raw_line("// FFI type definitions for NVENC (generated by bindgen).")
        .raw_line("// The library is loaded at runtime via libloading.")
        .raw_line("")
        .raw_line("pub type CUcontext = *mut std::ffi::c_void;")
        .generate()
        .expect("Failed to generate NVENC bindings");

    bindings.write_to_file(out_dir.join("sys.rs")).unwrap();
}
